pub const std = @import("std");
pub const geometry = @import("geometry");
pub const canvas = @import("root.zig");
pub const drawing_model = @import("drawing.zig");
pub const text_model = @import("text.zig");
pub const render_model = @import("render.zig");
pub const event_model = @import("events.zig");
pub const equality_model = @import("equality.zig");
pub const widget_runtime = @import("widget_runtime.zig");

pub const Error = canvas.Error;
pub const ObjectId = canvas.ObjectId;
pub const ImageId = canvas.ImageId;
pub const FontId = canvas.FontId;
pub const default_sans_font_id = canvas.default_sans_font_id;
pub const default_mono_font_id = canvas.default_mono_font_id;
pub const default_sans_font_family = canvas.default_sans_font_family;
pub const default_mono_font_family = canvas.default_mono_font_family;
pub const default_glyph_atlas_cache_retention_frames = canvas.default_glyph_atlas_cache_retention_frames;
pub const default_text_layout_cache_retention_frames = canvas.default_text_layout_cache_retention_frames;
pub const Color = canvas.Color;
pub const Affine = canvas.Affine;
pub const Radius = canvas.Radius;
pub const GradientStop = canvas.GradientStop;
pub const LinearGradient = canvas.LinearGradient;
pub const Fill = canvas.Fill;
pub const Stroke = canvas.Stroke;
pub const Clip = canvas.Clip;
pub const FillRect = canvas.FillRect;
pub const StrokeRect = canvas.StrokeRect;
pub const FillRoundedRect = canvas.FillRoundedRect;
pub const Line = canvas.Line;
pub const PathVerb = canvas.PathVerb;
pub const PathElement = canvas.PathElement;
pub const FillPath = canvas.FillPath;
pub const StrokePath = canvas.StrokePath;
pub const ImageFit = canvas.ImageFit;
pub const ImageSampling = canvas.ImageSampling;
pub const DrawImage = canvas.DrawImage;
pub const Shadow = canvas.Shadow;
pub const Blur = canvas.Blur;
pub const Glyph = canvas.Glyph;
pub const GlyphAtlasKey = canvas.GlyphAtlasKey;
pub const GlyphAtlasEntry = canvas.GlyphAtlasEntry;
pub const GlyphAtlasPlan = canvas.GlyphAtlasPlan;
pub const GlyphAtlasPlanner = canvas.GlyphAtlasPlanner;
pub const GlyphAtlasCacheEntry = canvas.GlyphAtlasCacheEntry;
pub const GlyphAtlasCacheActionKind = canvas.GlyphAtlasCacheActionKind;
pub const GlyphAtlasCacheAction = canvas.GlyphAtlasCacheAction;
pub const GlyphAtlasCachePlan = canvas.GlyphAtlasCachePlan;
pub const GlyphAtlasCachePlanner = canvas.GlyphAtlasCachePlanner;
pub const DrawText = canvas.DrawText;
pub const TextWrap = canvas.TextWrap;
pub const TextOverflow = canvas.TextOverflow;
pub const TextAlign = canvas.TextAlign;
pub const text_ellipsis = canvas.text_ellipsis;
pub const textEllipsisAdvance = canvas.textEllipsisAdvance;
pub const TextLayoutOptions = canvas.TextLayoutOptions;
pub const TextLine = canvas.TextLine;
pub const TextLayout = canvas.TextLayout;
pub const TextLayoutKey = canvas.TextLayoutKey;
pub const TextLayoutPlan = canvas.TextLayoutPlan;
pub const TextLayoutPlanSet = canvas.TextLayoutPlanSet;
pub const TextLayoutPlanner = canvas.TextLayoutPlanner;
pub const TextLayoutCacheEntry = canvas.TextLayoutCacheEntry;
pub const TextLayoutCacheActionKind = canvas.TextLayoutCacheActionKind;
pub const TextLayoutCacheAction = canvas.TextLayoutCacheAction;
pub const TextLayoutCachePlan = canvas.TextLayoutCachePlan;
pub const TextLayoutCachePlanner = canvas.TextLayoutCachePlanner;
pub const TextRange = canvas.TextRange;
pub const TextSelectionRect = canvas.TextSelectionRect;
pub const TextSelection = canvas.TextSelection;
pub const TextCaretDirection = canvas.TextCaretDirection;
pub const TextCaretMove = canvas.TextCaretMove;
pub const TextCompositionUpdate = canvas.TextCompositionUpdate;
pub const TextInputEvent = canvas.TextInputEvent;
pub const TextEditState = canvas.TextEditState;
pub const CanvasCommand = canvas.CanvasCommand;
pub const CommandRef = canvas.CommandRef;
pub const DiffKind = canvas.DiffKind;
pub const DiffChange = canvas.DiffChange;
pub const Builder = canvas.Builder;
pub const max_render_state_stack = canvas.max_render_state_stack;
pub const RenderState = canvas.RenderState;
pub const RenderCommand = canvas.RenderCommand;
pub const CanvasRenderOverride = canvas.CanvasRenderOverride;
pub const CanvasRenderAnimation = canvas.CanvasRenderAnimation;
pub const applyRenderOverrides = canvas.applyRenderOverrides;
pub const renderOverrideDirtyBounds = canvas.renderOverrideDirtyBounds;
pub const RenderPlan = canvas.RenderPlan;
pub const RenderPlanner = canvas.RenderPlanner;
pub const RenderPipelineKind = canvas.RenderPipelineKind;
pub const RenderBatch = canvas.RenderBatch;
pub const RenderBatchPlanner = canvas.RenderBatchPlanner;
pub const RenderBatchPlan = canvas.RenderBatchPlan;
pub const RenderPipelineCacheEntry = canvas.RenderPipelineCacheEntry;
pub const RenderPipelineCacheActionKind = canvas.RenderPipelineCacheActionKind;
pub const RenderPipelineCacheAction = canvas.RenderPipelineCacheAction;
pub const RenderPipelineCachePlanner = canvas.RenderPipelineCachePlanner;
pub const RenderPipelineCachePlan = canvas.RenderPipelineCachePlan;
pub const RenderPathGeometryKind = canvas.RenderPathGeometryKind;
pub const RenderPathGeometry = canvas.RenderPathGeometry;
pub const RenderPathGeometryPlan = canvas.RenderPathGeometryPlan;
pub const RenderPathGeometryPlanner = canvas.RenderPathGeometryPlanner;
pub const RenderPathGeometryKey = canvas.RenderPathGeometryKey;
pub const RenderPathGeometryCacheEntry = canvas.RenderPathGeometryCacheEntry;
pub const RenderPathGeometryCacheActionKind = canvas.RenderPathGeometryCacheActionKind;
pub const RenderPathGeometryCacheAction = canvas.RenderPathGeometryCacheAction;
pub const RenderPathGeometryCachePlan = canvas.RenderPathGeometryCachePlan;
pub const RenderPathGeometryCachePlanner = canvas.RenderPathGeometryCachePlanner;
pub const RenderImage = canvas.RenderImage;
pub const RenderImagePlan = canvas.RenderImagePlan;
pub const RenderImagePlanner = canvas.RenderImagePlanner;
pub const RenderImageKey = canvas.RenderImageKey;
pub const RenderImageCacheEntry = canvas.RenderImageCacheEntry;
pub const RenderImageCacheActionKind = canvas.RenderImageCacheActionKind;
pub const RenderImageCacheAction = canvas.RenderImageCacheAction;
pub const RenderImageCachePlan = canvas.RenderImageCachePlan;
pub const RenderImageCachePlanner = canvas.RenderImageCachePlanner;
pub const RenderResourceKind = canvas.RenderResourceKind;
pub const RenderResource = canvas.RenderResource;
pub const RenderResourcePlan = canvas.RenderResourcePlan;
pub const RenderResourcePlanner = canvas.RenderResourcePlanner;
pub const RenderResourceKey = canvas.RenderResourceKey;
pub const RenderResourceCacheEntry = canvas.RenderResourceCacheEntry;
pub const RenderResourceCacheActionKind = canvas.RenderResourceCacheActionKind;
pub const RenderResourceCacheAction = canvas.RenderResourceCacheAction;
pub const RenderResourceCachePlan = canvas.RenderResourceCachePlan;
pub const RenderResourceCachePlanner = canvas.RenderResourceCachePlanner;
pub const RenderLayer = canvas.RenderLayer;
pub const RenderLayerPlan = canvas.RenderLayerPlan;
pub const RenderLayerPlanner = canvas.RenderLayerPlanner;
pub const RenderLayerKey = canvas.RenderLayerKey;
pub const RenderLayerCacheEntry = canvas.RenderLayerCacheEntry;
pub const RenderLayerCacheActionKind = canvas.RenderLayerCacheActionKind;
pub const RenderLayerCacheAction = canvas.RenderLayerCacheAction;
pub const RenderLayerCachePlan = canvas.RenderLayerCachePlan;
pub const RenderLayerCachePlanner = canvas.RenderLayerCachePlanner;
pub const VisualEffectKind = canvas.VisualEffectKind;
pub const VisualEffect = canvas.VisualEffect;
pub const VisualEffectPlan = canvas.VisualEffectPlan;
pub const VisualEffectPlanner = canvas.VisualEffectPlanner;
pub const VisualEffectKey = canvas.VisualEffectKey;
pub const VisualEffectCacheEntry = canvas.VisualEffectCacheEntry;
pub const VisualEffectCacheActionKind = canvas.VisualEffectCacheActionKind;
pub const VisualEffectCacheAction = canvas.VisualEffectCacheAction;
pub const VisualEffectCachePlan = canvas.VisualEffectCachePlan;
pub const VisualEffectCachePlanner = canvas.VisualEffectCachePlanner;
pub const CanvasFrameOptions = canvas.CanvasFrameOptions;
pub const CanvasFrameStorage = canvas.CanvasFrameStorage;
pub const CanvasFrameBudget = canvas.CanvasFrameBudget;
pub const CanvasFrameBudgetStatus = canvas.CanvasFrameBudgetStatus;
pub const CanvasFrameDiagnostics = canvas.CanvasFrameDiagnostics;
pub const CanvasFrameProfileRisk = canvas.CanvasFrameProfileRisk;
pub const CanvasFrameProfile = canvas.CanvasFrameProfile;
pub const CanvasRenderPass = canvas.CanvasRenderPass;
pub const CanvasFrame = canvas.CanvasFrame;
pub const buildCanvasFrame = canvas.buildCanvasFrame;
pub const CanvasRenderPassLoadAction = canvas.CanvasRenderPassLoadAction;
pub const RenderEncoderBeginPass = canvas.RenderEncoderBeginPass;
pub const RenderEncoderCommand = canvas.RenderEncoderCommand;
pub const RenderEncoderPlan = canvas.RenderEncoderPlan;
pub const RenderEncoderPlanner = canvas.RenderEncoderPlanner;
pub const CanvasGpuCommandKind = canvas.CanvasGpuCommandKind;
pub const CanvasGpuRoundedRect = canvas.CanvasGpuRoundedRect;
pub const CanvasGpuStrokeRect = canvas.CanvasGpuStrokeRect;
pub const CanvasGpuLine = canvas.CanvasGpuLine;
pub const CanvasGpuShape = canvas.CanvasGpuShape;
pub const CanvasGpuPaint = canvas.CanvasGpuPaint;
pub const CanvasGpuImage = canvas.CanvasGpuImage;
pub const CanvasGpuText = canvas.CanvasGpuText;
pub const CanvasGpuShadow = canvas.CanvasGpuShadow;
pub const CanvasGpuBlur = canvas.CanvasGpuBlur;
pub const CanvasGpuEffect = canvas.CanvasGpuEffect;
pub const CanvasGpuCommand = canvas.CanvasGpuCommand;
pub const CanvasGpuPacket = canvas.CanvasGpuPacket;
pub const CanvasGpuPacketSummary = canvas.CanvasGpuPacketSummary;
pub const CanvasGpuPacketPlanner = canvas.CanvasGpuPacketPlanner;
pub const ReferenceImage = canvas.ReferenceImage;
pub const ReferenceRenderSurface = canvas.ReferenceRenderSurface;
pub const Density = canvas.Density;
pub const Easing = canvas.Easing;
pub const ColorScheme = canvas.ColorScheme;
pub const ColorContrast = canvas.ColorContrast;
pub const ThemeOptions = canvas.ThemeOptions;
pub const ColorTokens = canvas.ColorTokens;
pub const FontFamily = canvas.FontFamily;
pub const TypographyTokens = canvas.TypographyTokens;
pub const SpacingTokens = canvas.SpacingTokens;
pub const RadiusTokens = canvas.RadiusTokens;
pub const StrokeTokens = canvas.StrokeTokens;
pub const ShadowToken = canvas.ShadowToken;
pub const ShadowTokens = canvas.ShadowTokens;
pub const BlurTokens = canvas.BlurTokens;
pub const MotionDuration = canvas.MotionDuration;
pub const MotionAnimationOptions = canvas.MotionAnimationOptions;
pub const MotionTokens = canvas.MotionTokens;
pub const SpringToken = canvas.SpringToken;
pub const BlurTokenRef = canvas.BlurTokenRef;
pub const ScrollPhysics = canvas.ScrollPhysics;
pub const ScrollState = canvas.ScrollState;
pub const VirtualListOptions = canvas.VirtualListOptions;
pub const VirtualListRange = canvas.VirtualListRange;
pub const virtualListRange = canvas.virtualListRange;
pub const LayerTokens = canvas.LayerTokens;
pub const PixelSnapTokens = canvas.PixelSnapTokens;
pub const ControlVisualTokens = canvas.ControlVisualTokens;
pub const ControlTokens = canvas.ControlTokens;
pub const ColorTokenOverrides = canvas.ColorTokenOverrides;
pub const TypographyTokenOverrides = canvas.TypographyTokenOverrides;
pub const SpacingTokenOverrides = canvas.SpacingTokenOverrides;
pub const RadiusTokenOverrides = canvas.RadiusTokenOverrides;
pub const StrokeTokenOverrides = canvas.StrokeTokenOverrides;
pub const ShadowTokenOverrides = canvas.ShadowTokenOverrides;
pub const ShadowTokensOverrides = canvas.ShadowTokensOverrides;
pub const BlurTokenOverrides = canvas.BlurTokenOverrides;
pub const SpringTokenOverrides = canvas.SpringTokenOverrides;
pub const MotionTokenOverrides = canvas.MotionTokenOverrides;
pub const ScrollPhysicsOverrides = canvas.ScrollPhysicsOverrides;
pub const LayerTokenOverrides = canvas.LayerTokenOverrides;
pub const PixelSnapTokenOverrides = canvas.PixelSnapTokenOverrides;
pub const ControlVisualTokenOverrides = canvas.ControlVisualTokenOverrides;
pub const ControlTokenOverrides = canvas.ControlTokenOverrides;
pub const DesignTokenOverrides = canvas.DesignTokenOverrides;
pub const DesignTokens = canvas.DesignTokens;
pub const WidgetKind = canvas.WidgetKind;
pub const WidgetCursor = canvas.WidgetCursor;
pub const WidgetState = canvas.WidgetState;
pub const WidgetRenderState = canvas.WidgetRenderState;
pub const WidgetMainAlignment = canvas.WidgetMainAlignment;
pub const WidgetCrossAlignment = canvas.WidgetCrossAlignment;
pub const WidgetLayoutStyle = canvas.WidgetLayoutStyle;
pub const WidgetStyle = canvas.WidgetStyle;
pub const WidgetVariant = canvas.WidgetVariant;
pub const WidgetSize = canvas.WidgetSize;
pub const WidgetRole = canvas.WidgetRole;
pub const BuiltinComponentStyle = canvas.BuiltinComponentStyle;
pub const BuiltinComponentKind = canvas.BuiltinComponentKind;
pub const builtin_component_kinds = canvas.builtin_component_kinds;
pub const builtin_component_names = canvas.builtin_component_names;
pub const BuiltinComponentDescriptor = canvas.BuiltinComponentDescriptor;
pub const builtinComponentCount = canvas.builtinComponentCount;
pub const builtinComponentName = canvas.builtinComponentName;
pub const builtinComponentDescriptor = canvas.builtinComponentDescriptor;
pub const WidgetActions = canvas.WidgetActions;
pub const WidgetSemantics = canvas.WidgetSemantics;
pub const Widget = canvas.Widget;
pub const BuiltinComponentOptions = canvas.BuiltinComponentOptions;
pub const WidgetCommandPart = canvas.WidgetCommandPart;
pub const BuiltinSurfacePlacementOptions = canvas.BuiltinSurfacePlacementOptions;
pub const BuiltinSurfaceBackdropOptions = canvas.BuiltinSurfaceBackdropOptions;
pub const BuiltinStatusBarOptions = canvas.BuiltinStatusBarOptions;
pub const BuiltinSurfaceEnterAnimationOptions = canvas.BuiltinSurfaceEnterAnimationOptions;
pub const builtinComponentWidget = canvas.builtinComponentWidget;
pub const widgetCommandPartId = canvas.widgetCommandPartId;
pub const builtinSurfaceBackdropWidget = canvas.builtinSurfaceBackdropWidget;
pub const builtinStatusBarWidget = canvas.builtinStatusBarWidget;
pub const builtinSurfaceFrame = canvas.builtinSurfaceFrame;
pub const appendBuiltinSurfaceEnterAnimations = canvas.appendBuiltinSurfaceEnterAnimations;
pub const builtinSurfaceEnterOffset = canvas.builtinSurfaceEnterOffset;
pub const max_widget_depth = canvas.max_widget_depth;
pub const max_widget_text_range_rects = canvas.max_widget_text_range_rects;
pub const WidgetLayoutNode = canvas.WidgetLayoutNode;
pub const WidgetHit = canvas.WidgetHit;
pub const WidgetPointerPhase = canvas.WidgetPointerPhase;
pub const WidgetPointerEvent = canvas.WidgetPointerEvent;
pub const WidgetKeyboardPhase = canvas.WidgetKeyboardPhase;
pub const WidgetKeyboardModifiers = canvas.WidgetKeyboardModifiers;
pub const WidgetKeyboardEvent = canvas.WidgetKeyboardEvent;
pub const WidgetControlIntentKind = canvas.WidgetControlIntentKind;
pub const WidgetControlIntent = canvas.WidgetControlIntent;
pub const WidgetSemanticAction = canvas.WidgetSemanticAction;
pub const WidgetFileDropEvent = canvas.WidgetFileDropEvent;
pub const WidgetDragEvent = canvas.WidgetDragEvent;
pub const WidgetEventPhase = canvas.WidgetEventPhase;
pub const WidgetEventRouteEntry = canvas.WidgetEventRouteEntry;
pub const WidgetEventRoute = canvas.WidgetEventRoute;
pub const WidgetKeyboardRoute = canvas.WidgetKeyboardRoute;
pub const WidgetFocusDirection = canvas.WidgetFocusDirection;
pub const WidgetFocusTarget = canvas.WidgetFocusTarget;
pub const WidgetScrollMetrics = canvas.WidgetScrollMetrics;
pub const WidgetListMetrics = canvas.WidgetListMetrics;
pub const WidgetSemanticsNode = canvas.WidgetSemanticsNode;
pub const WidgetInvalidationKind = canvas.WidgetInvalidationKind;
pub const WidgetInvalidation = canvas.WidgetInvalidation;
pub const widgetKeyboardControlIntent = canvas.widgetKeyboardControlIntent;
pub const widgetSemanticControlIntent = canvas.widgetSemanticControlIntent;
pub const widgetSemanticControlIntentWithActions = canvas.widgetSemanticControlIntentWithActions;
pub const isWidgetActivationKey = canvas.isWidgetActivationKey;
pub const widgetSliderKeyboardValue = canvas.widgetSliderKeyboardValue;
pub const widgetScrollKeyboardIntent = canvas.widgetScrollKeyboardIntent;
pub const widgetScrollKeyboardDelta = canvas.widgetScrollKeyboardDelta;
pub const WidgetLayoutTree = canvas.WidgetLayoutTree;
pub const DisplayList = canvas.DisplayList;
pub const emitWidgetTree = canvas.emitWidgetTree;
pub const layoutWidgetTree = canvas.layoutWidgetTree;
pub const layoutWidgetTreeWithTokens = canvas.layoutWidgetTreeWithTokens;
pub const layoutTextRun = canvas.layoutTextRun;
pub const layoutTextRunPlan = canvas.layoutTextRunPlan;
pub const layoutTextCaretRect = canvas.layoutTextCaretRect;
pub const textCaretRectForLayout = canvas.textCaretRectForLayout;
pub const layoutTextSelectionRects = canvas.layoutTextSelectionRects;
pub const textSelectionRectsForLayout = canvas.textSelectionRectsForLayout;
pub const layoutTextOffsetForPoint = canvas.layoutTextOffsetForPoint;
pub const textOffsetForLayoutPoint = canvas.textOffsetForLayoutPoint;
pub const applyTextInputEvent = canvas.applyTextInputEvent;
pub const sampleCanvasRenderAnimations = canvas.sampleCanvasRenderAnimations;
pub const emitWidgetLayout = canvas.emitWidgetLayout;
pub const toggleWidgetKnobCommandId = canvas.toggleWidgetKnobCommandId;
pub const toggleWidgetKnobTravel = canvas.toggleWidgetKnobTravel;
pub const textSelectionForWidgetPoint = canvas.textSelectionForWidgetPoint;
pub const textOffsetForWidgetPoint = canvas.textOffsetForWidgetPoint;
pub const textInputViewportForWidget = canvas.textInputViewportForWidget;
pub const textInputContentExtentForWidget = canvas.textInputContentExtentForWidget;
pub const textInputMaxScrollOffsetForWidget = canvas.textInputMaxScrollOffsetForWidget;
pub const clampedTextInputScrollOffsetForWidget = canvas.clampedTextInputScrollOffsetForWidget;
pub const intrinsicWidgetSize = canvas.intrinsicWidgetSize;
pub const cursorForWidgetHit = canvas.cursorForWidgetHit;
pub const cursorForWidgetTarget = canvas.cursorForWidgetTarget;
pub const WidgetTextGeometry = canvas.WidgetTextGeometry;
pub const textGeometryForWidget = canvas.textGeometryForWidget;
pub const virtualWidgetScrollContentExtent = canvas.virtualWidgetScrollContentExtent;
pub const virtualWidgetScrollContentExtentWithTokens = canvas.virtualWidgetScrollContentExtentWithTokens;
pub const writeCanvasGpuPacketJson = canvas.writeCanvasGpuPacketJson;

pub const strokeBounds = drawing_model.strokeBounds;
pub const shadowBounds = drawing_model.shadowBounds;
pub const semanticActions = event_model.semanticActions;
pub const defaultSemanticActions = event_model.defaultSemanticActions;
pub const defaultFocusable = event_model.defaultFocusable;
pub const textLineBounds = text_model.textLineBounds;
pub const textBounds = text_model.textBounds;
pub const TextMeasureProvider = text_model.TextMeasureProvider;
pub const measureTextWidthForFont = text_model.measureTextWidthForFont;
pub const measureTextAdvance = text_model.measureTextAdvance;
pub const estimateTextWidth = text_model.estimateTextWidth;
pub const estimateTextWidthForFont = text_model.estimateTextWidthForFont;
pub const estimateTextAdvanceForBytes = text_model.estimateTextAdvanceForBytes;
pub const estimatedGlyphAdvance = text_model.estimatedGlyphAdvance;
pub const snapTextSelection = text_model.snapTextSelection;
pub const snapTextRange = text_model.snapTextRange;
pub const nextTextOffset = text_model.nextTextOffset;
pub const nextTextLineEnd = text_model.nextTextLineEnd;
pub const isTextBreakByte = text_model.isTextBreakByte;
pub const textLineRange = text_model.textLineRange;
pub const textLineCaretX = text_model.textLineCaretX;
pub const motionProgress = render_model.motionProgress;
pub const renderImageFingerprint = render_model.renderImageFingerprint;
pub const renderImageFingerprintForResource = render_model.renderImageFingerprintForResource;
pub const commandsEqual = equality_model.commandsEqual;
pub const rectsEqual = equality_model.rectsEqual;
pub const optionalRectsEqual = equality_model.optionalRectsEqual;
pub const sizesEqual = equality_model.sizesEqual;
pub const insetsEqual = equality_model.insetsEqual;
pub const optionalColorsEqual = equality_model.optionalColorsEqual;
pub const radiiEqual = equality_model.radiiEqual;
pub const affinesEqual = equality_model.affinesEqual;
pub const optionalF32Equal = equality_model.optionalF32Equal;
pub const optionalTextSelectionsEqual = equality_model.optionalTextSelectionsEqual;
pub const optionalTextRangesEqual = equality_model.optionalTextRangesEqual;
pub const widgetPartId = widget_runtime.widgetPartId;
pub const colorWithAlpha = widget_runtime.colorWithAlpha;
pub const widgetControlHeight = widget_runtime.widgetControlHeight;
pub const textSelectionFillColor = widget_runtime.textSelectionFillColor;
pub const textSelectionTextColor = widget_runtime.textSelectionTextColor;
pub const textEditingInkColor = widget_runtime.textEditingInkColor;
pub const staticTextSelectionFillColor = widget_runtime.staticTextSelectionFillColor;
pub const transparentColor = widget_runtime.transparentColor;

pub fn expectRect(expected: geometry.RectF, actual: ?geometry.RectF) !void {
    try std.testing.expect(actual != null);
    try std.testing.expectEqualDeep(expected, actual.?);
}

pub fn expectRectApprox(expected: geometry.RectF, actual: ?geometry.RectF) !void {
    try std.testing.expect(actual != null);
    try std.testing.expectApproxEqAbs(expected.x, actual.?.x, 0.001);
    try std.testing.expectApproxEqAbs(expected.y, actual.?.y, 0.001);
    try std.testing.expectApproxEqAbs(expected.width, actual.?.width, 0.001);
    try std.testing.expectApproxEqAbs(expected.height, actual.?.height, 0.001);
}

pub fn expectPixelRgba8(expected: [4]u8, surface: ReferenceRenderSurface, x: usize, y: usize) !void {
    try std.testing.expectEqualDeep(expected, surface.pixelRgba8(x, y));
}

pub fn expectVisiblePixel(pixel: [4]u8) !void {
    try std.testing.expect(pixel[3] > 0);
    try std.testing.expect(pixel[0] != 0 or pixel[1] != 0 or pixel[2] != 0);
}

pub fn referenceSurfaceSignature(pixels: []const u8) u64 {
    var hash: u64 = 14695981039346656037;
    for (pixels) |byte| {
        hash = (hash ^ byte) *% 1099511628211;
    }
    return hash;
}

pub fn expectLayoutFrame(layout: WidgetLayoutTree, id: ObjectId, expected: geometry.RectF) !void {
    const node = layout.findById(id) orelse return error.TestUnexpectedResult;
    try std.testing.expectEqualDeep(expected, node.frame);
}

pub fn expectRouteEntry(entry: WidgetEventRouteEntry, phase: WidgetEventPhase, id: ObjectId) !void {
    try std.testing.expectEqual(phase, entry.phase);
    try std.testing.expectEqual(id, entry.id);
}

pub fn expectFillColor(expected: Color, actual: Fill) !void {
    switch (actual) {
        .color => |color| try std.testing.expectEqualDeep(expected, color),
        else => return error.TestUnexpectedResult,
    }
}

pub fn expectGpuPaintColor(expected: Color, actual: CanvasGpuPaint) !void {
    switch (actual) {
        .color => |color| try std.testing.expectEqualDeep(expected, color),
        else => return error.TestUnexpectedResult,
    }
}
