//! soundboard model: the committed music catalog plus the playback,
//! search, navigation, and theming state the views bind to.
//!
//! The library is REAL data: `music_manifest.zon` (generated by
//! tools/prepare-example-music.sh and committed) is imported as a typed
//! value and flattened at comptime into the album/track tables below.
//! Albums carry a variable number of tracks, so each album records where
//! its run of tracks starts and how long it is — nothing here assumes a
//! fixed per-album stride.
//!
//! Playback is REAL audio through the runtime audio effect family:
//! pressing play issues `fx.playAudio` for the track's file and every
//! report — the load acknowledgment, coarse position ticks (with the
//! stream's honest buffering flag), the one completion at natural end,
//! failures — arrives as an `.audio_event` Msg through the ordinary
//! update path. Positions are the player's real clock and drive the
//! elapsed display; the player's DURATION reports are estimates for
//! this catalog and never replace the manifest total (the duration
//! rule, documented on `handleAudioEvent`). The audio files themselves are
//! gitignored (the prepare script produces them), and sources resolve
//! in a fixed order: the prepared LOCAL file, then a verified CACHE
//! entry, then a progressive STREAM from the catalog's URL base that
//! fills the cache for next time. The committed manifest ships a hosted
//! URL base, so a fresh clone streams on demand with zero setup; only
//! with the base explicitly cleared (NATIVE_SDK_MUSIC_URL_BASE set
//! empty) does a missing file surface as the honest "assets not
//! prepared" notice. With a base configured, a `.failed` means the
//! stream itself died (offline with a cold cache) and the notice says
//! so instead — browsing the catalog never needs the mp3s.
//!
//! Everything the views show that is computable — filtered lists,
//! progress fractions, time labels — is derived per rebuild into the
//! build arena, never stored.
//!
//! Fixed capacities (loud by design, documented in the README):
//!   - the manifest's albums and tracks (comptime-flattened)
//!   - one registered cover image per album (of the runtime's 16 slots)
//!   - 16-entry play-next queue (a full queue drops the request, noted
//!     in `queue_dropped` so the UI could surface it)
//!   - 48-byte search buffer

const std = @import("std");
const native_sdk = @import("native_sdk");

const canvas = native_sdk.canvas;

pub const Effects = native_sdk.Effects(Msg);

// ------------------------------------------------------------------ library

/// The manifest's shape, typed so the zon import is checked field by
/// field at comptime — a drifted manifest is a compile error, not a
/// runtime surprise.
pub const ManifestTrack = struct { title: []const u8, file: []const u8, duration_ms: u32, bytes: u64 };
pub const ManifestAlbum = struct { artist: []const u8, title: []const u8, year: u16, art: ?[]const u8, tracks: []const ManifestTrack };
pub const Catalog = struct { version: u32, url_base: ?[]const u8, albums: []const ManifestAlbum };

/// The committed catalog. Track `file` paths are relative to assets/;
/// album `art` paths are relative to src/ (the committed covers).
pub const catalog: Catalog = @import("music_manifest.zon");

pub const Album = struct {
    /// 1-based id; the registered cover `ImageId` matches it.
    id: u8,
    title: []const u8,
    artist: []const u8,
    year: u16,
    /// Cover fallback initials while the image is unregistered, derived
    /// from the album title at comptime.
    initials: []const u8,
    /// Committed cover path relative to src/, or null when the album
    /// shipped without art (initials stay, never a broken image).
    art: ?[]const u8,
    /// This album's run inside the flattened `tracks` table. Albums have
    /// VARIABLE track counts, so slicing is the only honest lookup — no
    /// fixed stride exists.
    track_start: u8,
    track_count: u8,
};

pub const Track = struct {
    /// 1-based id, unique across the library (also the audio effect key).
    id: u8,
    album: u8,
    /// 1-based position within the album.
    number: u8,
    title: []const u8,
    /// Playback path relative to the example root ("assets/" + the
    /// manifest's file), concatenated at comptime.
    path: []const u8,
    /// The manifest's relative file path ("music/<album>/<track>.mp3"),
    /// doubling as the track's URL path under the streaming base.
    file: []const u8,
    /// The manifest's duration, MEASURED from the intact source file by
    /// the prepare script — the total every surface displays and the
    /// seek math uses. The platform player's self-reported duration
    /// never replaces it: see `handleAudioEvent` for why that number is
    /// an estimate for this catalog.
    duration_ms: u32,
    /// The prepared file's exact byte size — the cache integrity gate
    /// for streamed plays (a cache entry whose size disagrees never
    /// plays; it is discarded and re-streamed).
    bytes: u64,
};

/// First letters of the title's first two words, uppercased — the cover
/// fallback the avatar shows while no image is registered.
fn initialsOf(comptime title: []const u8) []const u8 {
    comptime {
        var out: []const u8 = "";
        var word_start = true;
        for (title) |char| {
            if (char == ' ') {
                word_start = true;
                continue;
            }
            if (word_start and out.len < 2) out = out ++ &[_]u8{std.ascii.toUpper(char)};
            word_start = false;
        }
        return out;
    }
}

const total_tracks = blk: {
    var count: usize = 0;
    for (catalog.albums) |album| count += album.tracks.len;
    break :blk count;
};

/// The album table, flattened from the manifest at comptime with
/// sequential 1-based ids and each album's track run recorded.
pub const albums = blk: {
    var out: [catalog.albums.len]Album = undefined;
    var track_start: usize = 0;
    for (catalog.albums, 0..) |album, index| {
        out[index] = .{
            .id = index + 1,
            .title = album.title,
            .artist = album.artist,
            .year = album.year,
            .initials = initialsOf(album.title),
            .art = album.art,
            .track_start = track_start,
            .track_count = album.tracks.len,
        };
        track_start += album.tracks.len;
    }
    break :blk out;
};

/// The flattened track table: album order, sequential 1-based ids, and
/// each track's ready-to-play path baked at comptime.
pub const tracks = blk: {
    var out: [total_tracks]Track = undefined;
    var index: usize = 0;
    for (catalog.albums, 0..) |album, album_index| {
        for (album.tracks, 0..) |track, position| {
            out[index] = .{
                .id = index + 1,
                .album = album_index + 1,
                .number = position + 1,
                .title = track.title,
                .path = "assets/" ++ track.file,
                .file = track.file,
                .duration_ms = track.duration_ms,
                .bytes = track.bytes,
            };
            index += 1;
        }
    }
    break :blk out;
};

pub fn albumById(id: u8) *const Album {
    return &albums[id - 1];
}

pub fn trackById(id: u8) *const Track {
    return &tracks[id - 1];
}

pub fn albumTracks(album_id: u8) []const Track {
    const album = albumById(album_id);
    const start: usize = album.track_start;
    return tracks[start .. start + album.track_count];
}

// -------------------------------------------------------------- capacities

pub const max_queue = 16;
pub const max_search = 48;
/// The header bar's natural height, and the floor `header_height` falls
/// back to when no titlebar band overlays the content (fullscreen,
/// standard chrome, tests). Matches the tall hidden-inset band the
/// system reports through `on_chrome` — the band must not be taller
/// than the OS band, or the header's controls center below the traffic
/// lights the system centers within its own band.
pub const header_natural_height: f32 = 52;
/// The window's content min-width floor (main.zig declares it on the
/// shell window) and the default `canvas_width` before the first
/// presented frame reports the real surface size. Defaulting to the
/// FLOOR is deliberate: a tree built before any frame arrives (boot,
/// tree-level tests, the layout audit's smallest swept size) derives an
/// album grid that fits the narrowest window the shell allows — it can
/// underfill a wider surface for one frame, never overflow a narrow one.
pub const min_canvas_width: f32 = 1056;

/// The pre-first-frame `canvas_width` the MOBILE entry seeds instead
/// (main.zig's `initModel`): a mainstream phone-portrait width, so the
/// installing frame on a phone already composes the compact shell — the
/// full-screen mobile host has no window min-width to seed from, and
/// seeding the desktop floor would flash a desktop tree onto a 390pt
/// surface for one frame. The first presented frame corrects the value
/// exactly like the desktop seed; only the boot frame reads it.
pub const compact_seed_canvas_width: f32 = 390;

/// Which shell the root view composes. The two shells share every
/// content piece (tiles, rows, headings, the now-playing bindings) and
/// differ only in composition: `regular` is the desktop shape (wide
/// header bar, adaptive multi-column grid, full transport rail),
/// `compact` the phone shape (stacked touch header, mini player,
/// safe-area padding).
pub const FormFactor = enum { compact, regular };

/// Effect keys, model-owned identity (effect-key style). Audio playback
/// keys are the track ids themselves — one key namespace per channel.
pub const copy_key: u64 = 2;

/// The honest degraded state when a track's file cannot load AND no
/// URL base is configured to stream it (the audio assets are
/// gitignored; the prepare script produces them). Reachable only with
/// streaming explicitly disabled — the committed manifest ships a
/// hosted URL base — but when it is, the now-playing bar shows both
/// lines so the user knows exactly what to run — never a crash, never
/// silence, and the catalog browses fine.
pub const assets_missing_title = "music assets not prepared";
pub const assets_missing_hint = "run tools/prepare-example-music.sh";

/// The honest degraded state when a STREAM fails (a URL base is
/// configured, the local file was absent, and the network let the
/// playback down — offline with a cold cache, a dead host, a mid-flight
/// drop). Distinct from the assets notice on purpose: the remedy is
/// different.
pub const stream_failed_title = "stream unavailable";
pub const stream_failed_hint = "check the connection and try again";

/// The artist line while a stream is stalled waiting for bytes — the
/// honest state between "playing" and "paused" that only URL sources
/// have.
pub const buffering_hint = "buffering…";

/// Streaming configuration bounds: the URL base (manifest `.url_base`,
/// overridable with NATIVE_SDK_MUSIC_URL_BASE at launch) and the
/// platform cache directory resolved in main. Longer values are
/// REFUSED whole at set time, never truncated — a truncated URL would
/// stream garbage politely.
pub const max_url_base = 256;
pub const max_cache_dir = 512;

/// The manifest's committed streaming base ("" when null): the model
/// default the env override replaces at launch.
pub const manifest_url_base: []const u8 = catalog.url_base orelse "";

// ------------------------------------------------------------------- model

pub const Tab = enum { albums, songs };

/// One presented frame's clock, delivered through `on_frame` WHILE
/// PLAYING ONLY (main.zig gates it): the timestamp advances the rendered
/// playback clock between the player's coarse position ticks, and the
/// display's frame interval bounds the advance when frames were
/// irregular (occlusion, a resume after pause), so a stale gap can never
/// lurch the scrubber.
pub const FrameClock = struct {
    timestamp_ns: u64,
    interval_ns: u64,
};

/// How far the rendered clock may run AHEAD of a player position tick
/// before the disagreement stops being interpolation drift and gets
/// snapped. Drift per 500 ms tick is a few milliseconds; anything past a
/// full tick means reality changed (an external seek, a stall the
/// buffering flag has not reported yet), and honesty beats smoothness.
const position_snap_slack_ms: u32 = 600;

pub const Msg = union(enum) {
    show_albums,
    show_songs,
    set_appearance: native_sdk.Appearance,
    /// Chrome overlay geometry (tall hidden-inset titlebar): the header
    /// pads its leading edge past the traffic lights and matches its
    /// height to the titlebar band. Delivered through `on_chrome`.
    chrome_changed: native_sdk.WindowChrome,
    /// The canvas surface width, mirrored from presented frames through
    /// `on_frame` (main.zig emits it only when the width actually
    /// changed; unchanged-width frames instead carry the playback frame
    /// clock while audio moves, and nothing at all otherwise). The album
    /// grid derives its column count from this — the layout system's
    /// grid takes a FIXED column count and rows/columns never
    /// flow-wrap, so adapting to the window is the model's job: track
    /// the width, chunk in the view.
    canvas_resized: f32,
    search_edit: canvas.TextInputEvent,
    open_album: u8,
    close_album,
    play_album: u8,
    play_track: u8,
    /// Single click (and Space activation) on a track row: SELECTION
    /// only — playback needs the double click, Enter, or the transport.
    select_track: u8,
    /// Arrow keys through the app-level key fallback: the selection
    /// walks the track list on screen, clamped at its ends, without
    /// touching playback.
    select_next,
    select_previous,
    /// Enter through the app-level key fallback: play the selected
    /// track (toggling pause when it is already the loaded one).
    play_selected,
    /// One presented frame while playing (`on_frame` gates it): advances
    /// the rendered playback clock so the scrubber moves every frame,
    /// not every 500 ms position tick.
    frame_clock: FrameClock,
    toggle_play,
    next_track,
    prev_track,
    /// Seek slider changed; the reconciled value arrives through the
    /// `sync` hook (`seek_fraction`) before this message is applied.
    seeked,
    /// Every audio playback report: the load acknowledgment, position
    /// ticks, the one completion, and failures. Plain data — safe to
    /// read whole in update.
    audio_event: native_sdk.EffectAudio,
    /// Controlled scroll: each region's applied offset lands here and the
    /// view echoes it back, so a rebuild mid-gesture can never reset it.
    grid_scrolled: canvas.ScrollState,
    detail_scrolled: canvas.ScrollState,
    songs_scrolled: canvas.ScrollState,
    /// Context menu: queue a track to play after the current one.
    queue_track: u8,
    /// Context menu: copy the track title to the clipboard via `pbcopy`
    /// (the effects channel has no clipboard call today).
    copy_title: u8,
    copied: native_sdk.EffectExit,

    /// Zig-only dispatch: the Zig-built views (album grid, track rows,
    /// context menus), the app-level key fallback, and the runtime
    /// channels (appearance, chrome, frames, audio, scroll echoes,
    /// process exits) send these — never a markup on-* event — so the
    /// dead-state lint must not ask for one.
    pub const view_unbound = .{
        "set_appearance", "chrome_changed", "canvas_resized",
        "open_album",     "close_album",    "play_album",
        "play_track",     "select_track",   "select_next",
        "select_previous", "play_selected", "frame_clock",
        "audio_event",    "grid_scrolled",  "detail_scrolled",
        "songs_scrolled", "queue_track",    "copy_title",
        "copied",
    };
};

pub const Model = struct {
    // Source-of-truth state only; everything else is derived per rebuild.
    tab: Tab = .albums,
    appearance: native_sdk.Appearance = .{},
    open_album: ?u8 = null,
    /// Controlled scroll offsets (album grid, album detail, all songs):
    /// the model observes the applied offset and echoes it back.
    grid_scroll: f32 = 0,
    detail_scroll: f32 = 0,
    /// Chrome overlay geometry from `on_chrome` (tall hidden-inset
    /// titlebar): the header leads with a spacer this wide so its
    /// controls clear the traffic lights, and matches its height to the
    /// titlebar band. Both fall back to the natural header when no band
    /// overlays the content (fullscreen, standard chrome, tests).
    chrome_leading: f32 = 0,
    /// The trailing twin: how far OS window controls overlay the
    /// header's END (Windows delivers the min/max/close cluster here;
    /// macOS reports zero). The header closes with a spacer this wide
    /// so the search field clears the caption buttons.
    chrome_trailing: f32 = 0,
    /// The chrome band heights at the surface's TOP and BOTTOM edges,
    /// stored raw (no header floor applied). On phones the window-chrome
    /// channel carries the SAFE AREAS — status bar / Dynamic Island
    /// above, home indicator below — and the compact shell pads exactly
    /// these so content never sits under either. The desktop shell reads
    /// the floored `header_height` derivation below instead and has no
    /// bottom band to clear, so these stay untouched there.
    chrome_top: f32 = 0,
    chrome_bottom: f32 = 0,
    /// The host-reported form factor from the window-chrome channel
    /// (`chrome_changed`), null until a host reports one. When present
    /// it OWNS the shell switch (`formFactor` below) and the width
    /// derivation becomes the fallback for hosts that never report —
    /// desktop windows, tests, older hosts. Sticky by design: a host
    /// that reported once keeps its last report (an explicit `.unknown`
    /// never arrives as a Msg payload worth erasing state over).
    host_form_factor: ?FormFactor = null,
    /// True while the host projects the declared chrome tabs as a REAL
    /// native tab bar (`chrome_changed` carries the flag). The compact
    /// header yields its in-canvas Albums/Songs switcher while set —
    /// one tab affordance on screen, the system's — and keeps it
    /// everywhere the declaration is inert.
    native_tabs: bool = false,
    header_height: f32 = header_natural_height,
    /// The live canvas width, from `canvas_resized`. Seeds at the window
    /// min-width floor (see `min_canvas_width`) so pre-first-frame trees
    /// fit the narrowest window; the first presented frame corrects it.
    canvas_width: f32 = min_canvas_width,
    songs_scroll: f32 = 0,
    now: ?u8 = null, // playing track id
    /// The SELECTED track id — the inverted accent row in track lists.
    /// Distinct from `now` on purpose: single click / arrows move the
    /// selection, only a double click, Enter, or the transport moves
    /// playback. Starting a track selects it too (the playing row is the
    /// current row), but selecting never plays.
    selected: ?u8 = null,
    playing: bool = false,
    /// The RENDERED playback clock (labels, scrubber, the motion window).
    /// While playing it advances every presented frame (`frame_clock`,
    /// bounded per-frame steps) and the player's coarse position ticks
    /// correct it: forward corrections apply, small backward ones hold
    /// flat (the bar never visibly rewinds mid-play), and only a
    /// past-slack disagreement snaps. Paused, buffering, and seeking
    /// snap exactly — interpolation exists only where there is motion.
    elapsed_ms: u32 = 0,
    /// The last `frame_clock` timestamp, the delta base for the rendered
    /// clock. Never reset: a stale gap (pause, occlusion, boot) is
    /// bounded by the frame-interval clamp in `advanceRenderedClock`.
    frame_ns: u64 = 0,
    /// The loaded track's TOTAL for display and seek math: the manifest
    /// duration, the same number the track lists render — the two
    /// surfaces must agree. The platform's self-reported duration never
    /// replaces a nonzero manifest value (it is an estimate for this
    /// catalog — see `handleAudioEvent`); only a track the manifest
    /// carries no duration for adopts the platform's report, since an
    /// estimated scrubber beats a dead one.
    now_duration_ms: u32 = 0,
    /// The platform player's own duration report, mirrored verbatim
    /// from the audio events: observable state for tests and debugging,
    /// and the fallback total above — never the displayed number while
    /// the manifest has one.
    platform_duration_ms: u32 = 0,
    /// A track's file failed to load (the gitignored audio assets are
    /// not prepared, no URL base is configured, or the platform has no
    /// audio playback): playback is cleared and the now-playing bar
    /// shows the prepare hint instead.
    assets_missing: bool = false,
    /// A STREAM failed (a URL base is configured and the network let
    /// the playback down): playback is cleared and the now-playing bar
    /// shows the connection hint instead of the prepare hint.
    stream_failed: bool = false,
    /// The stream is stalled waiting for network bytes — mirrored from
    /// the audio events' buffering flag so the bar can show the honest
    /// third state between playing and paused. Local files never set it.
    buffering: bool = false,
    /// The streaming URL base: the manifest's committed value (the
    /// hosted catalog mirror, so streaming works out of the box) until
    /// main overrides it from NATIVE_SDK_MUSIC_URL_BASE. Empty means
    /// local-only playback (the variable set empty disables streaming).
    url_base_buffer: [max_url_base]u8 = blk: {
        var buffer: [max_url_base]u8 = @splat(0);
        @memcpy(buffer[0..manifest_url_base.len], manifest_url_base);
        break :blk buffer;
    },
    url_base_len: usize = manifest_url_base.len,
    /// The platform caches directory for this app (app_dirs `.cache`),
    /// resolved in main; the track cache lives in its audio/ child.
    /// Empty (tests, resolution failure) disables the cache — streams
    /// still play, they just never persist.
    cache_dir_buffer: [max_cache_dir]u8 = @splat(0),
    cache_dir_len: usize = 0,
    queue: [max_queue]u8 = @splat(0),
    queue_len: usize = 0,
    queue_dropped: u32 = 0,
    search_buffer: canvas.TextBuffer(max_search) = .{},
    /// Seek slider value, mirrored from the runtime through `sync`.
    seek_fraction: f32 = 0,
    /// Registered cover ImageIds, index = album id - 1; 0 while the
    /// decode/registration has not succeeded (avatars fall back to
    /// initials, so a failed decode can never break the UI).
    covers: [albums.len]canvas.ImageId = @splat(0),
    /// Copy-to-clipboard bookkeeping: how many pbcopy spawns finished ok.
    copies_done: u32 = 0,
    copy_failed: bool = false,

    /// Read by the ZIG-BUILT views (grid, detail, track rows), update
    /// logic, or main's launch wiring — never bound in markup — so
    /// opting them out keeps `native check`'s dead-state lint quiet
    /// without weakening it for real drift. The markup fragments bind
    /// the derived fns (`nowPlayingTitle`, `playPauseIcon`,
    /// `progressFraction`, ...) instead of these backing stores.
    pub const view_unbound = .{
        "tab",             "open_album",     "grid_scroll",
        "detail_scroll",   "canvas_width",   "songs_scroll",
        "now",             "selected",       "playing",
        "elapsed_ms",      "frame_ns",       "now_duration_ms",
        "platform_duration_ms",
        "assets_missing",  "stream_failed",  "buffering",
        "url_base_len",    "cache_dir_len",  "queue_dropped",
        "seek_fraction",   "copies_done",    "copy_failed",
        "appearance",      "search_buffer",  "url_base_buffer",
        "cache_dir_buffer", "queue",         "covers",
        "chrome_top",      "chrome_bottom",  "host_form_factor",
        "native_tabs",     "urlBase",
        "cacheDir",        "streamingConfigured", "searching",
        "colorScheme",     "hasNowPlaying",  "playingAlbum",
        "visibleAlbums",   "visibleTracks",  "miniBarVisible",
        "formFactor",
    };

    // ------------------------------------------------------------- queries

    pub fn search(model: *const Model) []const u8 {
        return model.search_buffer.text();
    }

    pub fn urlBase(model: *const Model) []const u8 {
        return model.url_base_buffer[0..model.url_base_len];
    }

    pub fn cacheDir(model: *const Model) []const u8 {
        return model.cache_dir_buffer[0..model.cache_dir_len];
    }

    /// Whether tracks can stream on demand: a URL base is configured
    /// (manifest or env). This is what turns the "assets not prepared"
    /// story into "streams on demand".
    pub fn streamingConfigured(model: *const Model) bool {
        return model.url_base_len > 0;
    }

    /// Install the streaming base (launch-time: env override or the
    /// manifest default). A trailing slash is trimmed so URL assembly
    /// is uniform; an over-long value is refused whole — a truncated
    /// base would stream garbage politely.
    pub fn setUrlBase(model: *Model, base: []const u8) void {
        const trimmed = std.mem.trimEnd(u8, base, "/");
        if (trimmed.len > max_url_base) return;
        @memcpy(model.url_base_buffer[0..trimmed.len], trimmed);
        model.url_base_len = trimmed.len;
    }

    /// Install the platform cache directory (launch-time). Over-long
    /// values are refused whole, leaving the cache disabled — honest
    /// degrade, streams still play.
    pub fn setCacheDir(model: *Model, dir: []const u8) void {
        if (dir.len > max_cache_dir) return;
        @memcpy(model.cache_dir_buffer[0..dir.len], dir);
        model.cache_dir_len = dir.len;
    }

    pub fn searching(model: *const Model) bool {
        return model.search().len > 0;
    }

    pub fn albumsShowing(model: *const Model) bool {
        return model.tab == .albums;
    }

    pub fn songsShowing(model: *const Model) bool {
        return model.tab == .songs;
    }

    pub fn colorScheme(model: *const Model) native_sdk.ColorScheme {
        return model.appearance.color_scheme;
    }

    pub fn coverFor(model: *const Model, album_id: u8) canvas.ImageId {
        return model.covers[album_id - 1];
    }

    pub fn nowTrack(model: *const Model) ?*const Track {
        const id = model.now orelse return null;
        return trackById(id);
    }

    /// The open album's title, for the detail page's markup heading
    /// (album_title.native binds it). Total over the model on purpose —
    /// markup bindings resolve on every rebuild — so it answers "" when
    /// no album is open (the grid page, where the fragment is not
    /// composed).
    pub fn openAlbumTitle(model: *const Model) []const u8 {
        const id = model.open_album orelse return "";
        return albumById(id).title;
    }

    pub fn hasNowPlaying(model: *const Model) bool {
        return model.now != null;
    }

    /// The shell rule: the HOST-REPORTED form factor owns the switch
    /// when a host has reported one (the window-chrome channel carries
    /// it, so it arrived as a Msg and replays with the journal); the
    /// width rule below is the fallback for hosts that never report —
    /// desktop windows, tests, older hosts.
    ///
    /// The width fallback, one strict comparison with no hysteresis:
    /// COMPACT strictly below the desktop shell's proven min content
    /// width (`min_canvas_width` — the floor the desktop layout audit
    /// sweeps from), the desktop shell at the floor and above. The
    /// boundary is honest by construction: every narrower surface is one
    /// the desktop composition has never been proven clean on (desktop
    /// windows enforce the floor, so only phone-class surfaces ever
    /// report less), and exactly AT the floor the audit proves the
    /// desktop shell clean. Both inputs are per-frame model state, so
    /// the same Msg sequence always lands the same shell.
    pub fn formFactor(model: *const Model) FormFactor {
        if (model.host_form_factor) |host| return host;
        return if (model.canvas_width < min_canvas_width) .compact else .regular;
    }

    /// Whether the compact shell's mini player is on screen: a track is
    /// loaded (playing OR paused — the bar must not vanish on pause), or
    /// a degraded playback notice needs a surface to read on (a failed
    /// load clears `now`, and the notice would otherwise be invisible on
    /// a phone with no persistent transport rail).
    pub fn miniBarVisible(model: *const Model) bool {
        return model.now != null or model.assets_missing or model.stream_failed;
    }

    pub fn idle(model: *const Model) bool {
        return model.now == null;
    }

    /// Data-driven icon choice for the transport's primary button: the
    /// markup binds `icon="{playPauseIcon}"`, so ONE button swaps its
    /// glyph with playback state - no if/else arms, no shared key to
    /// keep its identity stable.
    pub fn playPauseIcon(model: *const Model) []const u8 {
        return if (model.playing) "pause" else "play";
    }

    pub fn nowPlayingCover(model: *const Model) canvas.ImageId {
        const track = model.nowTrack() orelse return 0;
        return model.coverFor(track.album);
    }

    pub fn nowPlayingInitials(model: *const Model) []const u8 {
        const track = model.nowTrack() orelse return "--";
        return albumById(track.album).initials;
    }

    /// The bar's first line doubles as the status line: the honest
    /// assets-not-prepared notice replaces the track title after a load
    /// failure, so the user is told what to run instead of hearing
    /// nothing.
    pub fn nowPlayingTitle(model: *const Model) []const u8 {
        if (model.stream_failed) return stream_failed_title;
        if (model.assets_missing) return assets_missing_title;
        const track = model.nowTrack() orelse return "Nothing playing";
        return track.title;
    }

    pub fn nowPlayingArtist(model: *const Model) []const u8 {
        if (model.stream_failed) return stream_failed_hint;
        if (model.assets_missing) return assets_missing_hint;
        const track = model.nowTrack() orelse return "Pick an album or a song to start";
        // The honest third state: a stalled stream is not paused, but
        // nothing is coming out of the speakers either — say so where
        // the artist normally reads.
        if (model.buffering) return buffering_hint;
        return albumById(track.album).artist;
    }

    pub fn progressFraction(model: *const Model) f32 {
        if (model.now == null or model.now_duration_ms == 0) return 0;
        const fraction = @as(f32, @floatFromInt(model.elapsed_ms)) / @as(f32, @floatFromInt(model.now_duration_ms));
        return std.math.clamp(fraction, 0, 1);
    }

    pub fn elapsedLabel(model: *const Model, arena: std.mem.Allocator) []const u8 {
        if (model.now == null) return "-:--";
        return formatMs(arena, model.elapsed_ms);
    }

    pub fn durationLabel(model: *const Model, arena: std.mem.Allocator) []const u8 {
        if (model.now == null) return "-:--";
        return formatMs(arena, model.now_duration_ms);
    }

    /// Albums matching the search query, derived into the build arena.
    pub fn visibleAlbums(model: *const Model, arena: std.mem.Allocator) []const AlbumCell {
        const out = arena.alloc(AlbumCell, albums.len) catch return &.{};
        var count: usize = 0;
        for (&albums) |*album| {
            if (!model.albumMatches(album)) continue;
            out[count] = .{
                .id = album.id,
                .title = album.title,
                .artist = album.artist,
                .initials = album.initials,
                .cover = model.coverFor(album.id),
                .playing = model.playingAlbum() == album.id,
            };
            count += 1;
        }
        return out[0..count];
    }

    /// Library tracks matching the search query (title, artist, or album),
    /// derived into the build arena.
    pub fn visibleTracks(model: *const Model, arena: std.mem.Allocator) []const TrackRow {
        const out = arena.alloc(TrackRow, tracks.len) catch return &.{};
        var count: usize = 0;
        for (&tracks) |*track| {
            if (!model.trackMatches(track)) continue;
            out[count] = model.trackRow(arena, track, .with_album);
            count += 1;
        }
        return out[0..count];
    }

    /// One album's tracks for the detail view (never search-filtered: the
    /// detail page is the whole record).
    pub fn albumTrackRows(model: *const Model, arena: std.mem.Allocator, album_id: u8) []const TrackRow {
        const album_tracks = albumTracks(album_id);
        const out = arena.alloc(TrackRow, album_tracks.len) catch return &.{};
        for (album_tracks, 0..) |*track, index| {
            out[index] = model.trackRow(arena, track, .number_only);
        }
        return out;
    }

    pub fn playingAlbum(model: *const Model) u8 {
        const track = model.nowTrack() orelse return 0;
        return if (model.playing) track.album else 0;
    }

    fn albumMatches(model: *const Model, album: *const Album) bool {
        const query = model.search();
        if (query.len == 0) return true;
        return containsIgnoreCase(album.title, query) or containsIgnoreCase(album.artist, query);
    }

    fn trackMatches(model: *const Model, track: *const Track) bool {
        const query = model.search();
        if (query.len == 0) return true;
        const album = albumById(track.album);
        return containsIgnoreCase(track.title, query) or
            containsIgnoreCase(album.artist, query) or
            containsIgnoreCase(album.title, query);
    }

    const TrackRowStyle = enum { with_album, number_only };

    fn trackRow(model: *const Model, arena: std.mem.Allocator, track: *const Track, style: TrackRowStyle) TrackRow {
        const album = albumById(track.album);
        return .{
            .id = track.id,
            .number = std.fmt.allocPrint(arena, "{d}", .{track.number}) catch "",
            .title = track.title,
            .subtitle = switch (style) {
                .with_album => std.fmt.allocPrint(arena, "{s} — {s}", .{ album.artist, album.title }) catch "",
                .number_only => "",
            },
            .duration = formatMs(arena, track.duration_ms),
            .now = model.now == track.id,
            .playing = model.now == track.id and model.playing,
            .selected = model.selected == track.id,
            .queued = model.isQueued(track.id),
        };
    }

    fn isQueued(model: *const Model, track_id: u8) bool {
        for (model.queue[0..model.queue_len]) |queued| {
            if (queued == track_id) return true;
        }
        return false;
    }

    // ------------------------------------------------------------ mutation

    fn pushQueue(model: *Model, track_id: u8) void {
        if (model.isQueued(track_id)) return;
        if (model.queue_len >= max_queue) {
            model.queue_dropped += 1;
            return;
        }
        model.queue[model.queue_len] = track_id;
        model.queue_len += 1;
    }

    fn popQueue(model: *Model) ?u8 {
        if (model.queue_len == 0) return null;
        const next = model.queue[0];
        for (model.queue[1..model.queue_len], 0..) |moved, slot| {
            model.queue[slot] = moved;
        }
        model.queue_len -= 1;
        return next;
    }
};

pub const AlbumCell = struct {
    id: u8,
    title: []const u8,
    artist: []const u8,
    initials: []const u8,
    cover: canvas.ImageId,
    playing: bool,
};

pub const TrackRow = struct {
    id: u8,
    number: []const u8,
    title: []const u8,
    subtitle: []const u8,
    duration: []const u8,
    /// This track is loaded in the now-playing bar (playing or paused).
    now: bool,
    playing: bool,
    /// This track is the SELECTION (accent row) — see `Model.selected`.
    selected: bool,
    queued: bool,
};

fn formatMs(arena: std.mem.Allocator, ms: u32) []const u8 {
    const total_seconds = ms / 1000;
    return std.fmt.allocPrint(arena, "{d}:{d:0>2}", .{ total_seconds / 60, total_seconds % 60 }) catch "";
}

fn containsIgnoreCase(haystack: []const u8, needle: []const u8) bool {
    if (needle.len == 0) return true;
    if (needle.len > haystack.len) return false;
    var index: usize = 0;
    while (index + needle.len <= haystack.len) : (index += 1) {
        if (std.ascii.eqlIgnoreCase(haystack[index .. index + needle.len], needle)) return true;
    }
    return false;
}

// ------------------------------------------------------------------ update

pub fn update(model: *Model, msg: Msg, fx: *Effects) void {
    switch (msg) {
        .show_albums => model.tab = .albums,
        .show_songs => model.tab = .songs,
        .set_appearance => |appearance| model.appearance = appearance,
        .chrome_changed => |chrome| {
            // Pad whichever edge the platform puts its window controls
            // on (macOS: traffic lights leading; Windows: min/max/close
            // trailing) — the unused edge arrives as an honest zero.
            model.chrome_leading = chrome.insets.left;
            model.chrome_trailing = chrome.insets.right;
            // The raw top/bottom bands, for the compact shell's
            // safe-area padding: on phones the same channel carries the
            // status bar / Dynamic Island above and the home indicator
            // below, and the compact shell pads exactly these.
            model.chrome_top = chrome.insets.top;
            model.chrome_bottom = chrome.insets.bottom;
            // Match the header to the titlebar band so its centered
            // controls share the traffic lights' centerline; the natural
            // height is the floor when no band overlays the content.
            model.header_height = @max(header_natural_height, chrome.insets.top);
            // Host-reported form factor: adopt when the host says one
            // (sticky — see the field), leave the width fallback in
            // charge when it never does.
            switch (chrome.form_factor) {
                .compact => model.host_form_factor = .compact,
                .regular => model.host_form_factor = .regular,
                .unknown => {},
            }
            // Whether a native bar owns the tab affordance right now:
            // the compact header's switcher yields exactly while it is
            // projected.
            model.native_tabs = chrome.tabs_projected;
        },
        .canvas_resized => |width| model.canvas_width = width,
        .search_edit => |edit| model.search_buffer.apply(edit),
        .grid_scrolled => |state| model.grid_scroll = state.offset,
        .detail_scrolled => |state| model.detail_scroll = state.offset,
        .songs_scrolled => |state| model.songs_scroll = state.offset,
        .open_album => |id| {
            model.open_album = id;
            model.tab = .albums;
            // A fresh record opens at its top.
            model.detail_scroll = 0;
        },
        .close_album => model.open_album = null,
        .play_album => |id| startTrack(model, fx, albumTracks(id)[0].id),
        .play_track => |id| playOrToggle(model, fx, id),
        .select_track => |id| model.selected = id,
        .select_next => moveSelection(model, .next),
        .select_previous => moveSelection(model, .previous),
        .play_selected => {
            if (model.selected) |id| playOrToggle(model, fx, id);
        },
        .frame_clock => |frame| advanceRenderedClock(model, frame),
        .toggle_play => {
            if (model.now == null) {
                startTrack(model, fx, tracks[0].id);
            } else {
                setPlaying(model, fx, !model.playing);
            }
        },
        .next_track => advance(model, fx),
        .prev_track => previous(model, fx),
        .seeked => {
            if (model.now != null) {
                const duration: f32 = @floatFromInt(model.now_duration_ms);
                const target: u32 = @intFromFloat(std.math.clamp(model.seek_fraction, 0, 1) * duration);
                // Optimistic mirror for the labels; the platform seek has
                // no echo — the next position tick reports from there.
                model.elapsed_ms = target;
                fx.seekAudio(target);
            }
        },
        .audio_event => |event| handleAudioEvent(model, fx, event),
        .queue_track => |id| model.pushQueue(id),
        .copy_title => |id| fx.spawn(.{
            .key = copy_key,
            .argv = &.{"/usr/bin/pbcopy"},
            .stdin = trackById(id).title,
            .on_exit = Effects.exitMsg(.copied),
        }),
        .copied => |exit| {
            if (exit.reason == .exited and exit.code == 0) {
                model.copies_done += 1;
                model.copy_failed = false;
            } else {
                model.copy_failed = true;
            }
        },
    }
}

/// Every playback report flows through here. The audio key is the track
/// id, so a straggler for a track the model no longer plays is dropped
/// by identity — never misattributed to the current one.
///
/// THE DURATION RULE. Events carry the platform player's own duration
/// readout, and for this catalog that number is an ESTIMATE, never the
/// truth: the prepare script strips the seek header from every prepared
/// file (nothing of the source encoder may survive the strip), so a
/// decoder can only extrapolate the length from the bitrate it has seen
/// — a progressive stream's early guess has measured minutes wrong, and
/// even a fully local file reads seconds long and wobbles between
/// ticks. The manifest duration was measured from the intact SOURCE
/// file and matches a full decode exactly, so `now_duration_ms` (the
/// displayed total, the scrubber's denominator, the seek target's
/// scale) keeps the manifest value and the platform's report only lands
/// in `platform_duration_ms` — adopted as the total solely when the
/// manifest carries no duration at all. Positions are different:
/// position ticks are the player's REAL clock and stay authoritative.
fn handleAudioEvent(model: *Model, fx: *Effects, event: native_sdk.EffectAudio) void {
    const now = model.now orelse return;
    if (event.key != now) return;
    switch (event.kind) {
        .loaded => {
            adoptPlatformDuration(model, event.duration_ms);
            model.elapsed_ms = @intCast(event.position_ms);
            model.playing = event.playing;
            model.buffering = event.buffering;
        },
        .position => {
            const position: u32 = @intCast(event.position_ms);
            adoptPlatformDuration(model, event.duration_ms);
            // The stream's honest stall flag rides every tick; local
            // files always report false.
            model.buffering = event.buffering;
            // The coarse tick CORRECTS the frame-advanced rendered
            // clock. In motion, forward corrections apply and small
            // backward ones hold flat — the bar must never visibly
            // rewind because our frames ran a few ms ahead of the
            // player — while a past-slack disagreement is a real
            // desync (an external seek, an unreported stall) and
            // snaps. With no motion (paused, buffering) the tick is
            // simply the truth.
            if (model.playing and !model.buffering) {
                if (position > model.elapsed_ms or model.elapsed_ms - position > position_snap_slack_ms) {
                    model.elapsed_ms = position;
                }
            } else {
                model.elapsed_ms = position;
            }
        },
        // Real band-magnitude reports from hosts that analyze their own
        // playback. The soundboard draws no analyzer — its identity is
        // the clean catalog, not phosphor glass — so the reports are
        // consciously ignored (the deck is the surface that adopts
        // them).
        .spectrum => {},
        .completed => advance(model, fx),
        .failed, .rejected => {
            // Playback could not run. With a URL base configured the
            // local-file miss would have streamed, so a failure here
            // means the NETWORK let the playback down (offline with a
            // cold cache, a dead host, a mid-flight drop); without one
            // it means the gitignored assets are not prepared (or the
            // host has no audio playback). Two notices, two remedies —
            // and the catalog keeps browsing fine either way.
            if (model.streamingConfigured()) {
                model.stream_failed = true;
            } else {
                model.assets_missing = true;
            }
            model.now = null;
            model.playing = false;
            model.buffering = false;
            model.elapsed_ms = 0;
            model.now_duration_ms = 0;
            model.platform_duration_ms = 0;
        },
    }
}

/// Mirror the platform's duration report, and adopt it as the displayed
/// total ONLY when the manifest gave none (see the duration rule on
/// `handleAudioEvent`).
fn adoptPlatformDuration(model: *Model, reported_ms: u64) void {
    if (reported_ms == 0) return;
    const clamped: u32 = @intCast(@min(reported_ms, std.math.maxInt(u32)));
    model.platform_duration_ms = clamped;
    if (model.now_duration_ms == 0) model.now_duration_ms = clamped;
}

/// The play gesture on a specific track (double click, Enter, context
/// paths): a different track starts fresh, the loaded one toggles
/// play/pause in place. Either way the track becomes the selection —
/// the playing row is the current row.
fn playOrToggle(model: *Model, fx: *Effects, track_id: u8) void {
    model.selected = track_id;
    if (model.now == track_id) {
        setPlaying(model, fx, !model.playing);
    } else {
        startTrack(model, fx, track_id);
    }
}

const SelectionStep = enum { previous, next };

/// Whether a track sits in the track list currently on screen — the
/// domain the arrow-key selection walks. Songs tab: the search-filtered
/// library (the same predicate `visibleTracks` renders). Album detail:
/// the whole record, never filtered (matching `albumTrackRows`). The
/// album GRID shows no track list, so arrows move nothing there.
fn trackInCurrentList(model: *const Model, track: *const Track) bool {
    return switch (model.tab) {
        .songs => model.trackMatches(track),
        .albums => if (model.open_album) |album_id| track.album == album_id else false,
    };
}

/// Move the selection one row up or down the visible track list,
/// clamped at the ends (no wrap — arrows at an edge hold, they never
/// teleport). No selection yet (or one filtered out of view): down
/// enters at the top, up at the bottom. One pass over the flattened
/// track table, which IS view order for both list shapes.
fn moveSelection(model: *Model, step: SelectionStep) void {
    var first: ?u8 = null;
    var last: ?u8 = null;
    var before: ?u8 = null;
    var after: ?u8 = null;
    var seen_selected = false;
    for (&tracks) |*track| {
        if (!trackInCurrentList(model, track)) continue;
        if (first == null) first = track.id;
        last = track.id;
        if (model.selected == track.id) {
            seen_selected = true;
        } else if (!seen_selected) {
            before = track.id;
        } else if (after == null) {
            after = track.id;
        }
    }
    const target: ?u8 = switch (step) {
        .next => if (seen_selected) (after orelse model.selected) else first,
        .previous => if (seen_selected) (before orelse model.selected) else last,
    };
    if (target) |id| model.selected = id;
}

/// One presented frame while playing: advance the rendered clock by the
/// real frame delta, clamped to a few display intervals so a stale gap
/// (resume after pause, an occluded window, boot) steps gently instead
/// of lurching, and capped at the duration. Motion-gated twice — the
/// `on_frame` hook only emits the Msg while playing, and this re-checks
/// so a replayed journal straddling a pause boundary stays exact.
fn advanceRenderedClock(model: *Model, frame: FrameClock) void {
    const last = model.frame_ns;
    model.frame_ns = frame.timestamp_ns;
    if (!model.playing or model.now == null or model.buffering) return;
    const interval: u64 = if (frame.interval_ns > 0) frame.interval_ns else std.time.ns_per_s / 60;
    const delta_ns: u64 = if (last == 0 or frame.timestamp_ns <= last)
        interval
    else
        @min(frame.timestamp_ns - last, interval * 4);
    const advanced = @as(u64, model.elapsed_ms) + delta_ns / std.time.ns_per_ms;
    const limit: u64 = if (model.now_duration_ms > 0) model.now_duration_ms else advanced;
    model.elapsed_ms = @intCast(@min(advanced, limit));
}

fn startTrack(model: *Model, fx: *Effects, track_id: u8) void {
    const track = trackById(track_id);
    model.now = track_id;
    // Starting a track selects it: the playing row is the current row
    // for the arrow keys and the inverted accent register alike.
    model.selected = track_id;
    // `elapsed_ms` restarts here and advances with frame-clock messages
    // corrected by position events — it is also the motion clock for
    // the now-playing slide-in window, so animation gating replays
    // deterministically (no live clock read anywhere).
    model.elapsed_ms = 0;
    // The manifest's measured duration is the total for the whole
    // playback — the same number the track lists render, so the two
    // surfaces agree by construction (the duration rule on
    // `handleAudioEvent`). The platform's estimate mirror restarts too.
    model.now_duration_ms = track.duration_ms;
    model.platform_duration_ms = 0;
    // A fresh attempt clears the degraded notices; if the source is
    // still unplayable the `.failed` event raises the right one again.
    model.assets_missing = false;
    model.stream_failed = false;
    model.buffering = false;
    model.playing = true;
    // The source cascade rides ONE playAudio call: the prepared local
    // file first, then (URL base configured) the track's URL — where
    // the platform plays a verified cache entry locally or streams
    // progressively while filling the cache, keyed by the URL's hash
    // under the platform caches directory. `expected_bytes` is the
    // manifest's prepared size, the integrity gate that keeps partial
    // or stale cache entries from ever playing. The strings are copied
    // at call time, so stack buffers are fine here.
    var url_buffer: [max_url_base + 512]u8 = undefined;
    var url: []const u8 = "";
    if (model.streamingConfigured()) {
        url = std.fmt.bufPrint(&url_buffer, "{s}/{s}", .{ model.urlBase(), track.file }) catch "";
    }
    var cache_buffer: [max_cache_dir + 128]u8 = undefined;
    var cache_path: []const u8 = "";
    if (url.len > 0 and model.cacheDir().len > 0) {
        cache_path = native_sdk.audioCachePath(&cache_buffer, model.cacheDir(), url) catch "";
    }
    // One player total: a new playAudio replaces whatever played before,
    // and the track id keys every event back to this playback.
    fx.playAudio(.{
        .key = track_id,
        .path = track.path,
        .url = url,
        .cache_path = cache_path,
        .expected_bytes = track.bytes,
        .on_event = Effects.audioMsg(.audio_event),
    });
}

/// Play/pause drive the platform player in place; the optimistic flag
/// keeps the transport responsive and the next audio event confirms it.
fn setPlaying(model: *Model, fx: *Effects, playing: bool) void {
    model.playing = playing;
    if (playing) {
        fx.resumeAudio();
    } else {
        fx.pauseAudio();
    }
}

/// The play-next queue wins; otherwise the next track in the same album,
/// wrapping at the end of the record.
fn advance(model: *Model, fx: *Effects) void {
    if (model.popQueue()) |queued| {
        startTrack(model, fx, queued);
        return;
    }
    const track = model.nowTrack() orelse return;
    const album_tracks = albumTracks(track.album);
    const next_index = @as(usize, track.number) % album_tracks.len;
    startTrack(model, fx, album_tracks[next_index].id);
}

/// Restart the current track when it is a few seconds in; otherwise the
/// previous track in the album, wrapping backwards.
fn previous(model: *Model, fx: *Effects) void {
    const track = model.nowTrack() orelse return;
    if (model.elapsed_ms > 3000) {
        model.elapsed_ms = 0;
        fx.seekAudio(0);
        return;
    }
    const album_tracks = albumTracks(track.album);
    const prev_index = (@as(usize, track.number) + album_tracks.len - 2) % album_tracks.len;
    startTrack(model, fx, album_tracks[prev_index].id);
}
