//! deck model: the same committed music catalog as `examples/soundboard`
//! (one manifest, two skins — the "same app, different identity" contrast
//! is the point) plus the playback, search, and playlist-window state
//! the deck binds to.
//!
//! Playback is REAL: pressing play issues `fx.playAudio` against the
//! shared on-disk library and every report — the load acknowledgment,
//! coarse position ticks while playing, the one completion at natural
//! end, failures — arrives as an `.audio_event` Msg through the
//! ordinary update path. The progress clock (`elapsed_ms`) advances on
//! the presented-frame channel WHILE PLAYING (the soundboard's
//! frame-clock idiom: `on_frame` emits a journaled `frame_clock` Msg
//! per presented frame, so the spectrum and the marquee move at display
//! rate) and the player's coarse position ticks CORRECT it; pause,
//! stop, buffering, and idle starve the frame channel, so everything
//! derived from the clock freezes deterministically — same Msg
//! sequence, same glass. Positions are the player's real clock; the
//! player's DURATION reports are estimates for this catalog and never
//! replace the manifest total (the duration rule, documented on
//! `handleAudio`).
//!
//! The committed manifest ships a hosted URL base, so a missing local
//! file STREAMS on demand — a fresh clone plays with zero setup. Only
//! with streaming explicitly disabled (NATIVE_SDK_MUSIC_URL_BASE set
//! empty) does a failed load light the honest degraded state: the
//! display marquee stamps `NO MEDIA` and the channel line names the
//! remedy (`tools/prepare-example-music.sh`). With a base configured a
//! failure stamps `STREAM LOST` instead — a network problem, a network
//! remedy. Browsing and search never need the audio files — the catalog
//! is committed.
//!
//! Everything the views show that is computable — the filtered ledger,
//! timecode labels — is derived per rebuild into the build arena, never
//! stored. The 32-band spectrum is REAL: hosts that can analyze their
//! own playback deliver `.spectrum` audio events (32 band magnitudes,
//! journaled at the effect boundary like every position tick), the
//! model keeps the latest report as per-band targets, and the frame
//! clock runs analyzer ballistics over them (instant attack, linear
//! decay — see `band_decay_per_second`), so the glass stays smooth
//! between the host's ~25 Hz reports and replay repaints identical
//! bars. Pause starves both inputs and the bars FREEZE; stop and track
//! changes reset the glass; a host that cannot analyze never sends
//! bands and the display rests on its noise-floor comb — honest
//! absence, never fake dancing.
//!
//! Fixed capacities (loud by design, documented in the README):
//!   - the committed manifest's albums and tracks (comptime-derived
//!     tables; per-album track counts VARY, nothing assumes a stride)
//!   - 48-byte search buffer
//!   - 32 spectrum bands

const std = @import("std");
const native_sdk = @import("native_sdk");

const canvas = native_sdk.canvas;

pub const Effects = native_sdk.Effects(Msg);

// ---------------------------------------------------------------- manifest

/// The manifest's own shapes, matching `music_manifest.zon` (generated by
/// `tools/prepare-example-music.sh`; the deck's copy is byte-identical to
/// the soundboard's). Track `file` paths are relative to the
/// SOUNDBOARD's assets directory — the mp3s live once on disk and both
/// examples play the same files.
pub const ManifestTrack = struct { title: []const u8, file: []const u8, duration_ms: u32, bytes: u64 };
pub const ManifestAlbum = struct { artist: []const u8, title: []const u8, year: u16, art: ?[]const u8, tracks: []const ManifestTrack };
pub const Catalog = struct { version: u32, url_base: ?[]const u8, albums: []const ManifestAlbum };

/// The committed catalog: browsable without any gitignored audio on disk.
pub const catalog: Catalog = @import("music_manifest.zon");

/// Where the shared audio lives relative to the deck's working
/// directory: the soundboard's gitignored assets tree, prepared by
/// `tools/prepare-example-music.sh`.
pub const audio_root = "../soundboard/assets/";

pub const album_count = catalog.albums.len;
pub const track_count = blk: {
    var total: usize = 0;
    for (catalog.albums) |album| total += album.tracks.len;
    break :blk total;
};

// ------------------------------------------------------------------ library

pub const Album = struct {
    /// 1-based id; the registered cover image id derives from it
    /// (`main.coverImageId`).
    id: u8,
    title: []const u8,
    artist: []const u8,
    year: u16,
    /// Committed cover path relative to `src/` (null when the album's
    /// source art was absent at prepare time).
    art: ?[]const u8,
    /// This album's window into the flat `tracks` table. Counts VARY per
    /// album — never assume a stride.
    track_start: u16,
    track_count: u8,
};

pub const Track = struct {
    /// 1-based id, unique across the library.
    id: u8,
    album: u8,
    /// 1-based position within the album.
    number: u8,
    title: []const u8,
    /// Playable path (deck-relative into the soundboard's assets).
    path: []const u8,
    /// The manifest's relative file path, doubling as the track's URL
    /// path under the streaming base.
    file: []const u8,
    /// The manifest's duration, MEASURED from the intact source file by
    /// the prepare script — the total every surface displays and the
    /// seek math uses. The platform player's self-reported duration
    /// never replaces it: see `handleAudio` for why that number is an
    /// estimate for this catalog.
    duration_ms: u32,
    /// The prepared file's exact byte size — the cache integrity gate
    /// for streamed plays.
    bytes: u64,
};

/// Flat album table derived from the manifest at comptime: ids are
/// 1-based positions, and each album records its slice of the flat
/// track table (variable counts, no stride arithmetic anywhere).
pub const albums: [album_count]Album = blk: {
    var out: [album_count]Album = undefined;
    var start: usize = 0;
    for (catalog.albums, 0..) |album, index| {
        out[index] = .{
            .id = index + 1,
            .title = album.title,
            .artist = album.artist,
            .year = album.year,
            .art = album.art,
            .track_start = start,
            .track_count = album.tracks.len,
        };
        start += album.tracks.len;
    }
    break :blk out;
};

/// Flat track table derived from the manifest at comptime, in album
/// order; the playable path is the comptime concat of the shared assets
/// root and the manifest's soundboard-relative file.
pub const tracks: [track_count]Track = blk: {
    var out: [track_count]Track = undefined;
    var index: usize = 0;
    for (catalog.albums, 0..) |album, album_index| {
        for (album.tracks, 0..) |track, track_index| {
            out[index] = .{
                .id = index + 1,
                .album = album_index + 1,
                .number = track_index + 1,
                .title = track.title,
                .path = audio_root ++ track.file,
                .file = track.file,
                .duration_ms = track.duration_ms,
                .bytes = track.bytes,
            };
            index += 1;
        }
    }
    break :blk out;
};

pub fn albumById(id: u8) *const Album {
    return &albums[id - 1];
}

pub fn trackById(id: u8) *const Track {
    return &tracks[id - 1];
}

pub fn albumTracks(album_id: u8) []const Track {
    const album = albumById(album_id);
    const start: usize = album.track_start;
    return tracks[start .. start + album.track_count];
}

// -------------------------------------------------------------- capacities

pub const max_search = 48;
pub const spectrum_bands = 32;
/// Marquee geometry: visible window in characters, and how much
/// playback time advances the scroll by one character. 16 characters of
/// the pixel face at the full-grid marquee scale fit the display bay's
/// full interior width even when every glyph is the face's widest
/// (0.76 em) — the face is proportional, so the budget is worst-case
/// honest, not average-case hopeful.
pub const marquee_window = 16;
pub const marquee_step_ms: u32 = 500;

/// The honest degraded state the display wears after a failed load
/// with NO URL base configured: the marquee stamp, and the channel-line
/// remedy naming the script that prepares the shared gitignored audio.
/// The committed manifest ships a hosted base, so this is reachable
/// only with streaming explicitly disabled (NATIVE_SDK_MUSIC_URL_BASE
/// set empty).
pub const no_media_marquee = "NO MEDIA";
pub const no_media_remedy = "RUN TOOLS/PREPARE-EXAMPLE-MUSIC.SH";

/// The honest degraded state after a failed STREAM (a URL base is
/// configured, so the local-file miss streamed — and the network let
/// the deck down: offline with a cold cache, a dead host, a mid-flight
/// drop). Distinct stamp, distinct remedy.
pub const stream_failed_marquee = "STREAM LOST";
pub const stream_failed_remedy = "CHECK THE CONNECTION AND RETRY";

/// The marquee stamp while a stream is stalled waiting for bytes — the
/// honest state between playing and paused that only URL sources have.
pub const buffering_marquee = "BUFFERING";

/// Streaming configuration bounds (manifest `.url_base`, overridable
/// with NATIVE_SDK_MUSIC_URL_BASE at launch; the cache directory from
/// app_dirs). Over-long values are refused whole, never truncated.
pub const max_url_base = 256;
pub const max_cache_dir = 512;

/// The manifest's committed streaming base ("" when null): the model
/// default the env override replaces at launch.
pub const manifest_url_base: []const u8 = catalog.url_base orelse "";

/// Effect keys, model-owned identity (effect-key style). The audio
/// channel's key is the playing track's id — its own namespace, so it
/// never collides with the spawn key below.
pub const copy_key: u64 = 2;

/// The two windows' declared labels — the addresses the window-action
/// effects (`fx.closeWindow`/`fx.minimizeWindow`) resolve. One spelling:
/// main.zig's shell scene and windows_fn use these same constants.
pub const main_window_label = "main";
pub const playlist_window_label = "playlist";

/// Which window a skin-native window key addresses (the chromeless
/// chassis draws its own close/minimize controls in each cap band).
pub const WindowRef = enum { player, playlist };

/// One presented frame's clock reading, from the guarded `on_frame`
/// hook (main.zig): the timestamp advances the rendered playback clock
/// and the display's frame interval bounds the advance when frames were
/// irregular (occlusion, a resume after pause), so a stale gap can
/// never lurch the readouts.
pub const FrameClock = struct {
    timestamp_ns: u64,
    interval_ns: u64,
};

/// How far the rendered clock may run AHEAD of a player position tick
/// before the disagreement stops being interpolation drift and gets
/// snapped. Drift per 500 ms tick is a few milliseconds; anything past a
/// full tick means reality changed (an external seek, a stall the
/// buffering flag has not reported yet), and honesty beats smoothness.
const position_snap_slack_ms: u32 = 600;

/// The spectrum envelope: classic analyzer ballistics over the host's
/// band reports. A NEW report attacks instantly (a rising band jumps to
/// its target the moment the event lands — transients read as hits, not
/// fades), and every presented frame decays each displayed band toward
/// its target at this linear rate, so a falling band takes ~1/3 s from
/// full scale to floor — smooth at display rate between the host's
/// ~25 Hz reports. Both inputs (the `.spectrum` events and the
/// `frame_clock` Msgs) are journaled, so the envelope replays exactly.
pub const band_decay_per_second: f32 = 3.0;

// ------------------------------------------------------------------- model

pub const Msg = union(enum) {
    /// The PL key (and `primary+L`): the playlist window's open flag
    /// flips, and the windows_fn reconcile creates or closes the window.
    toggle_playlist,
    /// The USER closed the playlist window (through the skin's own
    /// close key or any OS route that survives chromeless): the window
    /// is already gone as an optimistic echo; the model agrees here.
    playlist_closed,
    /// A skin-native CLOSE key (the chromeless chassis draws its own
    /// window controls): the player's key closes the app's window for
    /// real through the window-action effect; the playlist's closes
    /// declaratively (presence in the declared set IS visibility).
    close_window: WindowRef,
    /// A skin-native MINIMIZE key: the real OS verb through the
    /// window-action effect — the window genies into the Dock.
    minimize_window: WindowRef,
    /// One presented frame while playing (guarded in main.onFrame): the
    /// rendered clock advances at display rate between position ticks.
    frame_clock: FrameClock,
    set_appearance: native_sdk.Appearance,
    search_edit: canvas.TextInputEvent,
    clear_search,
    play_track: u8,
    toggle_play,
    /// The dedicated PLAY key: starts from idle, resumes from pause,
    /// and is a no-op while already playing — a latching hardware key,
    /// not a toggle (`toggle_play` stays the space-bar/shortcut verb).
    transport_play,
    /// The dedicated PAUSE key: pauses only. Resume is PLAY's job.
    transport_pause,
    /// The STOP key: playback halts and the head returns to 0:00, but
    /// the track stays loaded — the classic stop-vs-pause distinction.
    stop,
    next_track,
    prev_track,
    /// Seek slider changed; the reconciled value arrives through the
    /// `sync` hook (`seek_fraction`) before this message is applied.
    seeked,
    /// Output volume slider changed; same sync-hook contract
    /// (`volume_fraction`). Rides through to the platform player.
    volume_changed,
    /// Every playback report from the audio effect channel: loaded,
    /// position ticks, the one completion, failures.
    audio_event: native_sdk.EffectAudio,
    /// Context menu: copy the track title to the clipboard via `pbcopy`
    /// (soundboard's effect, unchanged: the effects channel has no
    /// clipboard call today).
    copy_title: u8,
    copied: native_sdk.EffectExit,
};

pub const Model = struct {
    // Source-of-truth state only; everything else is derived per rebuild.
    /// The playlist window's visibility channel: `windows_fn` declares
    /// the window exactly while this is set (presence IS visibility).
    playlist_open: bool = false,
    appearance: native_sdk.Appearance = .{},
    now: ?u8 = null, // loaded track id
    playing: bool = false,
    /// The RENDERED playback clock — the one input every live display
    /// derives from (marquee, spectrum, timecode, segment digits).
    /// While playing it advances every presented frame (`frame_clock`,
    /// bounded per-frame steps) and the player's coarse position ticks
    /// correct it: forward corrections apply, small backward ones hold
    /// flat (the readouts never visibly rewind mid-play), and only a
    /// past-slack disagreement snaps. Paused, stopped, buffering, and
    /// seeking snap exactly — interpolation exists only where there is
    /// motion.
    elapsed_ms: u32 = 0,
    /// The last `frame_clock` timestamp, the delta base for the
    /// rendered clock. Never reset: a stale gap (pause, occlusion,
    /// boot) is bounded by the frame-interval clamp in
    /// `advanceRenderedClock`.
    frame_ns: u64 = 0,
    /// The loaded track's TOTAL for the timecode and seek math: the
    /// manifest duration, the same number the ledger renders — the two
    /// surfaces must agree. The platform's self-reported duration never
    /// replaces a nonzero manifest value (it is an estimate for this
    /// catalog — see `handleAudio`); only a track the manifest carries
    /// no duration for adopts the platform's report.
    now_duration_ms: u32 = 0,
    /// The platform player's own duration report, mirrored verbatim
    /// from the audio events: observable state for tests and debugging,
    /// and the fallback total above — never the displayed number while
    /// the manifest has one.
    platform_duration_ms: u32 = 0,
    /// A load failed (missing mp3s, no URL base, or a platform without
    /// audio): the display wears the NO MEDIA remedy until the next
    /// successful load attempt.
    media_failed: bool = false,
    /// A STREAM failed (URL base configured, network gone): the display
    /// wears the STREAM LOST remedy instead — different problem,
    /// different fix.
    stream_failed: bool = false,
    /// The stream is stalled waiting for network bytes, mirrored from
    /// the audio events' buffering flag; the marquee stamps BUFFERING
    /// while it holds. Local files never set it.
    buffering: bool = false,
    /// The streaming URL base (manifest default, env override at
    /// launch; empty = local-only) and the platform cache directory
    /// resolved in main — same conventions as the soundboard, one
    /// on-disk cache since both examples share the audio.
    url_base_buffer: [max_url_base]u8 = blk: {
        var buffer: [max_url_base]u8 = @splat(0);
        @memcpy(buffer[0..manifest_url_base.len], manifest_url_base);
        break :blk buffer;
    },
    url_base_len: usize = manifest_url_base.len,
    cache_dir_buffer: [max_cache_dir]u8 = @splat(0),
    cache_dir_len: usize = 0,
    search_buffer: canvas.TextBuffer(max_search) = .{},
    /// Seek slider value, mirrored from the runtime through `sync`.
    seek_fraction: f32 = 0,
    /// Output level, mirrored from the runtime through `sync` and
    /// applied to the platform player via `fx.setAudioVolume`.
    volume_fraction: f32 = 0.8,
    /// Copy-to-clipboard bookkeeping: how many pbcopy spawns finished ok.
    copies_done: u32 = 0,
    copy_failed: bool = false,
    /// Registered album cover ImageIds, index = album id - 1; 0 while
    /// unregistered (the strict test decoder has no JPEG codec, so under
    /// the null platform every slot stays 0 and the sleeve pane degrades
    /// to its engraved plate — asserted in the suite).
    covers: [album_count]canvas.ImageId = @splat(0),
    /// The spectrum glass, driven by REAL analysis: `band_targets` is
    /// the latest `.spectrum` report (each byte / 255), `band_levels`
    /// is what the chart draws — attacked instantly on report arrival,
    /// decayed toward the targets by the frame clock (see
    /// `band_decay_per_second`). Both journaled inputs, so replay
    /// repaints identical bars.
    band_targets: [spectrum_bands]f32 = @splat(0),
    band_levels: [spectrum_bands]f32 = @splat(0),
    /// Whether the CURRENT playback has delivered any `.spectrum`
    /// report. Until it does — idle deck, a host that cannot analyze,
    /// the instant before the first report — the glass shows the
    /// resting comb: honest absence, never fake dancing.
    spectrum_live: bool = false,

    // ------------------------------------------------------------- queries

    pub fn search(model: *const Model) []const u8 {
        return model.search_buffer.text();
    }

    pub fn searching(model: *const Model) bool {
        return model.search().len > 0;
    }

    pub fn playlistShowing(model: *const Model) bool {
        return model.playlist_open;
    }

    pub fn nowTrack(model: *const Model) ?*const Track {
        const id = model.now orelse return null;
        return trackById(id);
    }

    pub fn idle(model: *const Model) bool {
        return model.now == null;
    }

    /// Any degraded playback state, for the display's warning tint (the
    /// stamps themselves name which problem it is).
    pub fn mediaFailed(model: *const Model) bool {
        return model.media_failed or model.stream_failed;
    }

    /// The channel-line remedy matching the marquee's failure stamp.
    pub fn remedyText(model: *const Model) []const u8 {
        if (model.stream_failed) return stream_failed_remedy;
        return no_media_remedy;
    }

    pub fn urlBase(model: *const Model) []const u8 {
        return model.url_base_buffer[0..model.url_base_len];
    }

    pub fn cacheDir(model: *const Model) []const u8 {
        return model.cache_dir_buffer[0..model.cache_dir_len];
    }

    pub fn streamingConfigured(model: *const Model) bool {
        return model.url_base_len > 0;
    }

    /// Install the streaming base (launch-time). Trailing slash
    /// trimmed; over-long values refused whole, never truncated.
    pub fn setUrlBase(model: *Model, base: []const u8) void {
        const trimmed = std.mem.trimEnd(u8, base, "/");
        if (trimmed.len > max_url_base) return;
        @memcpy(model.url_base_buffer[0..trimmed.len], trimmed);
        model.url_base_len = trimmed.len;
    }

    /// Install the platform cache directory (launch-time). Over-long
    /// values leave the cache disabled — streams still play.
    pub fn setCacheDir(model: *Model, dir: []const u8) void {
        if (dir.len > max_cache_dir) return;
        @memcpy(model.cache_dir_buffer[0..dir.len], dir);
        model.cache_dir_len = dir.len;
    }

    pub fn coverFor(model: *const Model, album_id: u8) canvas.ImageId {
        return model.covers[album_id - 1];
    }

    /// The loaded track's registered cover, 0 when idle or unregistered
    /// (the sleeve pane degrades to its engraved plate).
    pub fn nowCover(model: *const Model) canvas.ImageId {
        const track = model.nowTrack() orelse return 0;
        return model.coverFor(track.album);
    }

    /// Status-strip counter: visible tracks over the library total.
    pub fn statusLabel(model: *const Model, arena: std.mem.Allocator) []const u8 {
        return std.fmt.allocPrint(arena, "{d}/{d} TRK", .{ model.visibleTracks(arena).len, tracks.len }) catch "";
    }

    /// Display channel readout: "TRK 07". Short by design — the album is
    /// already in the marquee, and the timecode rides the same line
    /// (round 1 caught the long form wrapping over the progress strip).
    pub fn channelLabel(model: *const Model, arena: std.mem.Allocator) []const u8 {
        const track = model.nowTrack() orelse return "TRK --";
        return std.fmt.allocPrint(arena, "TRK {d:0>2}", .{track.id}) catch "";
    }

    /// The source readout under the channel line: average bitrate and
    /// file size, BOTH computed from the committed manifest's real bytes
    /// and duration — the deck states what it can actually know about
    /// the stream and nothing more (no invented sample rates, no codec
    /// badges). Idle prints the powered-on dashes.
    pub fn sourceLabel(model: *const Model, arena: std.mem.Allocator) []const u8 {
        const track = model.nowTrack() orelse return "--- KBPS  --.- MB";
        const duration = model.now_duration_ms;
        if (duration == 0 or track.bytes == 0) return "--- KBPS  --.- MB";
        const kbps = (track.bytes * 8) / duration; // bytes*8 bits / ms = kbit/s
        const mb_tenths = (track.bytes * 10) / (1024 * 1024);
        return std.fmt.allocPrint(arena, "{d} KBPS  {d}.{d} MB", .{
            kbps, mb_tenths / 10, mb_tenths % 10,
        }) catch "";
    }

    /// The display marquee: title, artist, and album on one rotating line —
    /// the classic scroller, derived (never stored) as a pure function
    /// of the loaded track and the progress clock. The composed line
    /// rotates one step every `marquee_step_ms` of PLAYBACK time, so
    /// pause freezes it exactly like the spectrum (the position events
    /// stop, the clock stops) and the same model state always yields the
    /// same window of text. After a failed load the marquee stamps the
    /// NO MEDIA state instead.
    pub fn marqueeText(model: *const Model, arena: std.mem.Allocator) []const u8 {
        if (model.stream_failed) return stream_failed_marquee;
        if (model.media_failed) return no_media_marquee;
        if (model.buffering) return buffering_marquee;
        const track = model.nowTrack() orelse return "NO SIGNAL";
        const album = albumById(track.album);
        // ASCII-only composition: the rotation slices bytes, so a
        // multi-byte separator could split mid-codepoint at the seam.
        // 192 bytes cover the catalog's longest title/artist/album line.
        var compose_buffer: [192]u8 = undefined;
        var upper_buffer: [192]u8 = undefined;
        const line = std.fmt.bufPrint(&compose_buffer, "{s} /// {s} /// {s}  ", .{
            track.title, album.artist, album.title,
        }) catch return track.title;
        const full = upperTo(&upper_buffer, line);
        if (full.len <= marquee_window) return arena.dupe(u8, std.mem.trimEnd(u8, full, " /")) catch "";
        const offset = (model.elapsed_ms / marquee_step_ms) % full.len;
        const out = arena.alloc(u8, marquee_window) catch return "";
        for (out, 0..) |*byte, index| {
            byte.* = full[(offset + index) % full.len];
        }
        return out;
    }

    pub fn progressFraction(model: *const Model) f32 {
        if (model.now == null) return 0;
        if (model.now_duration_ms == 0) return 0;
        const fraction = @as(f32, @floatFromInt(model.elapsed_ms)) / @as(f32, @floatFromInt(model.now_duration_ms));
        return std.math.clamp(fraction, 0, 1);
    }

    pub fn elapsedLabel(model: *const Model, arena: std.mem.Allocator) []const u8 {
        if (model.now == null) return "--:--";
        return formatMs(arena, model.elapsed_ms);
    }

    pub fn durationLabel(model: *const Model, arena: std.mem.Allocator) []const u8 {
        if (model.now == null) return "--:--";
        return formatMs(arena, model.now_duration_ms);
    }

    /// The resting comb: the powered-on noise floor the glass wears
    /// whenever no real analysis is on it — idle deck, a host without
    /// `audio_spectrum`, the instant before the first report. A fixed
    /// pattern, so the display reads as live hardware rather than a
    /// dead widget, and honestly STILL: bands that are not measured do
    /// not dance.
    pub fn restingLevel(band: usize) f32 {
        return if (band % 4 == 0) 0.05 else 0.02;
    }

    /// One spectrum band's displayed level in [0, 1]: the envelope over
    /// the journaled `.spectrum` reports while real analysis is live,
    /// the resting comb otherwise. Model state only — pause starves the
    /// inputs and every reader freezes at once; replaying the journal
    /// paints the same glass.
    pub fn bandLevel(model: *const Model, band: usize) f32 {
        if (model.now == null or !model.spectrum_live) return restingLevel(band);
        return std.math.clamp(model.band_levels[band], 0, 1);
    }

    /// The 32 spectrum band levels, derived into the build arena per
    /// rebuild (the chart widget's one bar series binds this).
    pub fn spectrumLevels(model: *const Model, arena: std.mem.Allocator) []const f32 {
        const out = arena.alloc(f32, spectrum_bands) catch return &.{};
        for (out, 0..) |*level, band| level.* = model.bandLevel(band);
        return out;
    }

    /// Ledger rows: the whole library as ONE flat list, narrowed by the
    /// search query, derived into the build arena.
    pub fn visibleTracks(model: *const Model, arena: std.mem.Allocator) []const TrackRow {
        const out = arena.alloc(TrackRow, tracks.len) catch return &.{};
        var count: usize = 0;
        for (&tracks) |*track| {
            if (!model.trackMatches(track)) continue;
            out[count] = model.trackRow(arena, track);
            // The ledger rules BETWEEN rows only: the first visible row
            // carries no hairline above it (and the last none below).
            out[count].first = count == 0;
            count += 1;
        }
        return out[0..count];
    }

    fn trackMatches(model: *const Model, track: *const Track) bool {
        const query = model.search();
        if (query.len == 0) return true;
        const album = albumById(track.album);
        return containsIgnoreCase(track.title, query) or
            containsIgnoreCase(album.artist, query) or
            containsIgnoreCase(album.title, query);
    }

    fn trackRow(model: *const Model, arena: std.mem.Allocator, track: *const Track) TrackRow {
        const album = albumById(track.album);
        return .{
            .id = track.id,
            .number = std.fmt.allocPrint(arena, "{d:0>2}", .{track.id}) catch "",
            .title = track.title,
            .artist = album.artist,
            .duration = formatMs(arena, track.duration_ms),
            .now = model.now == track.id,
            .playing = model.now == track.id and model.playing,
        };
    }
};

pub const TrackRow = struct {
    id: u8,
    number: []const u8,
    title: []const u8,
    artist: []const u8,
    duration: []const u8,
    /// This track is loaded in the deck (playing or paused).
    now: bool,
    playing: bool,
    /// The ledger's first VISIBLE row: no hairline divider above it
    /// (rules run between rows only).
    first: bool = false,
};

fn formatMs(arena: std.mem.Allocator, ms: u32) []const u8 {
    const total_seconds = ms / 1000;
    return std.fmt.allocPrint(arena, "{d}:{d:0>2}", .{ total_seconds / 60, total_seconds % 60 }) catch "";
}

fn containsIgnoreCase(haystack: []const u8, needle: []const u8) bool {
    if (needle.len == 0) return true;
    if (needle.len > haystack.len) return false;
    var index: usize = 0;
    while (index + needle.len <= haystack.len) : (index += 1) {
        if (std.ascii.eqlIgnoreCase(haystack[index .. index + needle.len], needle)) return true;
    }
    return false;
}

/// ASCII-uppercase into a fixed buffer (library titles are ASCII); the
/// caller's arena copy happens in the formatting call.
fn upperTo(buffer: []u8, source: []const u8) []const u8 {
    const len = @min(buffer.len, source.len);
    for (source[0..len], 0..) |byte, index| {
        buffer[index] = std.ascii.toUpper(byte);
    }
    return buffer[0..len];
}

// ------------------------------------------------------------------ update

pub fn update(model: *Model, msg: Msg, fx: *Effects) void {
    switch (msg) {
        .toggle_playlist => model.playlist_open = !model.playlist_open,
        .playlist_closed => model.playlist_open = false,
        .close_window => |ref| switch (ref) {
            // The player IS the app: its close key performs the REAL
            // window close through the window-action effect, and the
            // app exits by the host's existing last-window semantics.
            .player => fx.closeWindow(main_window_label),
            // The playlist rack closes DECLARATIVELY: presence in the
            // declared window set is visibility, so clearing the flag
            // IS the close (the reconcile tears the window down) — the
            // same machinery the PL key rides.
            .playlist => model.playlist_open = false,
        },
        // Minimize is the real OS verb on either unit — nothing
        // declarative models "in the Dock", so both ride the effect.
        .minimize_window => |ref| fx.minimizeWindow(switch (ref) {
            .player => main_window_label,
            .playlist => playlist_window_label,
        }),
        .frame_clock => |frame| advanceRenderedClock(model, frame),
        .set_appearance => |appearance| model.appearance = appearance,
        .search_edit => |edit| model.search_buffer.apply(edit),
        .clear_search => model.search_buffer.apply(.clear),
        .play_track => |id| {
            if (model.now == id) {
                setPlaying(model, fx, !model.playing);
            } else {
                startTrack(model, fx, id);
            }
        },
        .toggle_play => {
            if (model.now == null) {
                startTrack(model, fx, tracks[0].id);
            } else {
                setPlaying(model, fx, !model.playing);
            }
        },
        .transport_play => {
            if (model.now == null) {
                startTrack(model, fx, tracks[0].id);
            } else if (!model.playing) {
                setPlaying(model, fx, true);
            }
        },
        .transport_pause => {
            if (model.now != null and model.playing) setPlaying(model, fx, false);
        },
        .stop => {
            if (model.now != null) {
                // Halt AND rewind, keeping the record loaded: pause the
                // platform player, seek it home, and zero the progress
                // clock so everything derived from it (marquee,
                // timecode) returns to the top deterministically. The
                // spectrum glass RESTS (stop clears the analyzer, the
                // classic stop-vs-pause distinction: pause freezes the
                // bars, stop puts the comb back).
                model.playing = false;
                model.elapsed_ms = 0;
                resetSpectrum(model);
                fx.pauseAudio();
                fx.seekAudio(0);
            }
        },
        .next_track => advance(model, fx),
        .prev_track => previous(model, fx),
        .seeked => {
            if (model.now != null) {
                const duration: f32 = @floatFromInt(model.now_duration_ms);
                const target: u32 = @intFromFloat(std.math.clamp(model.seek_fraction, 0, 1) * duration);
                // Optimistic clock move; the platform's next position
                // tick reports from the sought point and re-confirms it.
                model.elapsed_ms = target;
                fx.seekAudio(target);
            }
        },
        .volume_changed => {
            model.volume_fraction = std.math.clamp(model.volume_fraction, 0, 1);
            fx.setAudioVolume(model.volume_fraction);
        },
        .audio_event => |event| handleAudio(model, fx, event),
        .copy_title => |id| fx.spawn(.{
            .key = copy_key,
            .argv = &.{"/usr/bin/pbcopy"},
            .stdin = trackById(id).title,
            .on_exit = Effects.exitMsg(.copied),
        }),
        .copied => |exit| {
            if (exit.reason == .exited and exit.code == 0) {
                model.copies_done += 1;
                model.copy_failed = false;
            } else {
                model.copy_failed = true;
            }
        },
    }
}

/// One playback report from the audio channel. Events carry the key the
/// channel resolved them against; a straggler for a replaced track (the
/// deck already started something else) is dropped rather than applied
/// to the wrong record.
///
/// THE DURATION RULE (shared with the soundboard — one catalog, one
/// rule). Events carry the platform player's own duration readout, and
/// for this catalog that number is an ESTIMATE, never the truth: the
/// prepare script strips the seek header from every prepared file
/// (nothing of the source encoder may survive the strip), so a decoder
/// can only extrapolate the length from the bitrate it has seen — a
/// progressive stream's early guess has measured minutes wrong, and
/// even a fully local file reads seconds long and wobbles between
/// ticks. The manifest duration was measured from the intact SOURCE
/// file and matches a full decode exactly, so `now_duration_ms` (the
/// timecode total, the progress denominator, the seek target's scale)
/// keeps the manifest value and the platform's report only lands in
/// `platform_duration_ms` — adopted as the total solely when the
/// manifest carries no duration at all. Positions are different:
/// position ticks are the player's REAL clock and stay authoritative.
fn handleAudio(model: *Model, fx: *Effects, event: native_sdk.EffectAudio) void {
    const id = model.now orelse return;
    if (event.key != @as(u64, id)) return;
    switch (event.kind) {
        .loaded => {
            adoptPlatformDuration(model, event.duration_ms);
            model.buffering = event.buffering;
        },
        .position => {
            const position = clampMs(event.position_ms);
            adoptPlatformDuration(model, event.duration_ms);
            // The stream's honest stall flag rides every tick.
            model.buffering = event.buffering;
            // The coarse tick CORRECTS the frame-advanced rendered
            // clock. In motion, forward corrections apply and small
            // backward ones hold flat — the readouts must never visibly
            // rewind because our frames ran a few ms ahead of the
            // player — while a past-slack disagreement is a real desync
            // (an external seek, an unreported stall) and snaps. With
            // no motion (paused, buffering) the tick is simply the
            // truth.
            if (model.playing and !model.buffering) {
                if (position > model.elapsed_ms or model.elapsed_ms - position > position_snap_slack_ms) {
                    model.elapsed_ms = position;
                }
            } else {
                model.elapsed_ms = position;
            }
        },
        // Real analysis of the playing audio: the report becomes the
        // per-band targets, and a RISING band attacks instantly (the
        // frame clock only ever decays — see `advanceRenderedClock`).
        // The first report flips the glass from the resting comb to
        // live bars; pause simply stops the reports, so the last-drawn
        // bars hold — freeze-on-pause with real data.
        .spectrum => {
            model.spectrum_live = true;
            for (event.bands, 0..) |band, index| {
                const target = @as(f32, @floatFromInt(band)) / 255.0;
                model.band_targets[index] = target;
                if (target > model.band_levels[index]) model.band_levels[index] = target;
            }
        },
        // Natural end: the next ledger row plays (see `advance`).
        .completed => advance(model, fx),
        // Playback could not run (`failed`), or the effects layer
        // refused the request (`rejected` — impossible for these
        // comptime paths, honest anyway). With a URL base configured
        // the local-file miss would have streamed, so a failure means
        // the NETWORK let the deck down — STREAM LOST; without one the
        // shared assets are not prepared — NO MEDIA. Never a crash,
        // never silence.
        .failed, .rejected => {
            model.now = null;
            model.playing = false;
            model.buffering = false;
            model.elapsed_ms = 0;
            model.now_duration_ms = 0;
            model.platform_duration_ms = 0;
            resetSpectrum(model);
            if (model.streamingConfigured()) {
                model.stream_failed = true;
            } else {
                model.media_failed = true;
            }
        },
    }
}

fn clampMs(ms: u64) u32 {
    return @intCast(@min(ms, std.math.maxInt(u32)));
}

/// Mirror the platform's duration report, and adopt it as the displayed
/// total ONLY when the manifest gave none (see the duration rule on
/// `handleAudio`).
fn adoptPlatformDuration(model: *Model, reported_ms: u64) void {
    if (reported_ms == 0) return;
    const clamped = clampMs(reported_ms);
    model.platform_duration_ms = clamped;
    if (model.now_duration_ms == 0) model.now_duration_ms = clamped;
}

/// One presented frame while playing: advance the rendered clock by the
/// real frame delta, clamped to a few display intervals so a stale gap
/// (resume after pause, an occluded window, boot) steps gently instead
/// of lurching, and capped at the duration. Motion-gated twice — the
/// `on_frame` hook only emits the Msg while playing, and this re-checks
/// so a replayed journal straddling a pause boundary stays exact.
fn advanceRenderedClock(model: *Model, frame: FrameClock) void {
    const last = model.frame_ns;
    model.frame_ns = frame.timestamp_ns;
    if (!model.playing or model.now == null or model.buffering) return;
    const interval: u64 = if (frame.interval_ns > 0) frame.interval_ns else std.time.ns_per_s / 60;
    const delta_ns: u64 = if (last == 0 or frame.timestamp_ns <= last)
        interval
    else
        @min(frame.timestamp_ns - last, interval * 4);
    const advanced = @as(u64, model.elapsed_ms) + delta_ns / std.time.ns_per_ms;
    const limit: u64 = if (model.now_duration_ms > 0) model.now_duration_ms else advanced;
    model.elapsed_ms = @intCast(@min(advanced, limit));
    // Spectrum ballistics, the decay half (attack lives in the
    // `.spectrum` arm of `handleAudio`): each displayed band falls
    // linearly toward its latest reported target, on the same bounded
    // frame delta the clock advanced by — deterministic per journal,
    // frozen with the clock when nothing moves.
    if (model.spectrum_live) {
        const fall = band_decay_per_second *
            (@as(f32, @floatFromInt(delta_ns)) / @as(f32, std.time.ns_per_s));
        for (&model.band_levels, model.band_targets) |*level, target| {
            if (level.* > target) level.* = @max(target, level.* - fall);
        }
    }
}

/// Put the spectrum glass back on its resting comb: a new playback, a
/// stop, or a failure means the last-drawn bars no longer describe any
/// audio; the next `.spectrum` report flips it live again.
fn resetSpectrum(model: *Model) void {
    model.spectrum_live = false;
    model.band_targets = @splat(0);
    model.band_levels = @splat(0);
}

fn startTrack(model: *Model, fx: *Effects, track_id: u8) void {
    const track = trackById(track_id);
    model.now = track_id;
    model.elapsed_ms = 0;
    resetSpectrum(model);
    // The manifest's measured duration is the total for the whole
    // playback — the same number the ledger renders, so the two
    // surfaces agree by construction (the duration rule on
    // `handleAudio`). The platform's estimate mirror restarts too.
    model.now_duration_ms = track.duration_ms;
    model.platform_duration_ms = 0;
    // A fresh load attempt is the retry path out of the failure states.
    model.media_failed = false;
    model.stream_failed = false;
    model.buffering = false;
    model.playing = true;
    // The source cascade rides ONE playAudio call: the shared local
    // file first, then (URL base configured) the track's URL — verified
    // cache entry or progressive stream that fills the cache, keyed by
    // the URL's hash. `expected_bytes` is the manifest's prepared size,
    // the gate that keeps partial cache entries from ever playing.
    var url_buffer: [max_url_base + 512]u8 = undefined;
    var url: []const u8 = "";
    if (model.streamingConfigured()) {
        url = std.fmt.bufPrint(&url_buffer, "{s}/{s}", .{ model.urlBase(), track.file }) catch "";
    }
    var cache_buffer: [max_cache_dir + 128]u8 = undefined;
    var cache_path: []const u8 = "";
    if (url.len > 0 and model.cacheDir().len > 0) {
        cache_path = native_sdk.audioCachePath(&cache_buffer, model.cacheDir(), url) catch "";
    }
    // One player is the whole surface: a new playAudio replaces whatever
    // played before, and the track id is the channel key echoed in every
    // event for this playback.
    fx.playAudio(.{
        .key = track_id,
        .path = track.path,
        .url = url,
        .cache_path = cache_path,
        .expected_bytes = track.bytes,
        .on_event = Effects.audioMsg(.audio_event),
    });
    // Keep the platform player honest with the VOL fader from the very
    // first load (the channel default is full volume).
    fx.setAudioVolume(std.math.clamp(model.volume_fraction, 0, 1));
}

/// Play/pause ride the audio channel's transport: pause holds the
/// player in place (position events stop, so the clock and everything
/// derived from it freeze), resume continues from the same point.
fn setPlaying(model: *Model, fx: *Effects, playing: bool) void {
    model.playing = playing;
    if (playing) {
        fx.resumeAudio();
    } else {
        fx.pauseAudio();
    }
}

/// Natural end and the NEXT key both step the LEDGER: the catalog is
/// ONE flat song list on this deck (the playlist window shows exactly
/// that order), so advance plays the next row in the flat track table —
/// crossing album boundaries without a seam — and wraps from the last
/// row back to the first. Track ids ARE the flat 1-based positions, so
/// the wrap is id arithmetic on the full table.
fn advance(model: *Model, fx: *Effects) void {
    const track = model.nowTrack() orelse return;
    const next_index = @as(usize, track.id) % tracks.len;
    startTrack(model, fx, tracks[next_index].id);
}

/// Restart the current track when it is a few seconds in; otherwise the
/// previous ledger row, wrapping backwards from the first to the last —
/// the mirror of `advance`, on the same flat order.
fn previous(model: *Model, fx: *Effects) void {
    const track = model.nowTrack() orelse return;
    if (model.elapsed_ms > 3000) {
        model.elapsed_ms = 0;
        fx.seekAudio(0);
        return;
    }
    const prev_index = (@as(usize, track.id) + tracks.len - 2) % tracks.len;
    startTrack(model, fx, tracks[prev_index].id);
}
