import { componentPages } from "./components-pages";

export const PAGE_TITLES: Record<string, string> = {
  components: "Components",
  // One title per component page, from the shared inventory.
  ...Object.fromEntries(componentPages.map((page) => [`components/${page.slug}`, page.name])),
  "": "The Complete Toolkit\nfor Native Apps",
  introduction: "Introduction",
  "quick-start": "Quick Start",
  "app-model": "App Model",
  "native-ui": "Native UI",
  state: "State & Data Flow",
  theming: "Theming",
  "building-components": "Building Components",
  runtime: "App & Runtime",
  frontend: "Frontend Projects",
  "native-surfaces": "Native Surfaces",
  windows: "Windows",
  webviews: "Multiple WebViews",
  "keyboard-shortcuts": "Keyboard Shortcuts",
  commands: "Commands",
  bridge: "Bridge",
  "bridge/builtin-commands": "Builtin Commands",
  dialogs: "Dialogs",
  menus: "Menus",
  "native-controls": "Native Controls",
  "built-in-components": "Built-in Components",
  capabilities: "Capabilities",
  "platform-support": "Platform Support",
  tray: "System Tray",
  security: "Security",
  cli: "CLI",
  "cli/dev": "Dev Server",
  skills: "Agent Skills",
  packaging: "Packaging",
  "packaging/signing": "Code Signing",
  updates: "Updates",
  "app-zon": "Config",
  debugging: "Debugging",
  "debugging/doctor": "native doctor",
  automation: "Automation",
  testing: "Testing",
  "testing/ci": "Testing in CI",
  extensions: "Extensions",
  embed: "Embedded App",
  "web-engines": "Web Engines",
  packages: "Package Distribution",
};

export function getPageTitle(slug: string): string | null {
  return slug in PAGE_TITLES ? PAGE_TITLES[slug]! : null;
}
